### ISSUE TITLE
Multiobjective UDP

### ISSUE THREAD

**Issue by osm3000** [esa/pagmo2#124]
Hi, 
Thank you so much for the superb work you've done!
Can you please provide an example for a multiobjective UDP? I tried simply to add the other objectives to the return list from `fitness` function, but it always complains that this is s single-objective function, and thus i should return a list of length 1
Best Regards,
Omar

**Comment by darioizzo** [comment]
You can refer to the python tutorial on multi objective UDPs. Or read the documentation of the class problem to see what methods can be implemented in you UDP to specify its nature.

In a nutshell, pagmo/pygmo assume by default, one objective. You can override this default behaviour implementing a method ``get_nobj`` and returning (eg) 2
