### ISSUE TITLE
Feature: Add IHS algorithm from Pagmo 1.1.7

### ISSUE THREAD

**Issue by arita37** [esa/pagmo2#125]
Hello,
Thanks for good work.

It seems that IHS algorihtm is not available in PAGMO 2.0:
http://pagmo.sourceforge.net/pygmo/documentation/algorithms.html#PyGMO.algorithm.ihs

Is there a way to integrate IHS into Pagmo 2.0

thanks

**Comment by darioizzo** [comment]
Sure, it's quite straightforward .... will likely be added for v2.5

**Comment by darioizzo** [comment]
Btw, if you want to have a go a PR is welcome ....

**Comment by arita37** [comment]
Ok,, tahnks
Reason was it may solve some Mixed Integer Problems....
Am not sure if there is a way to incorporate some Mixed Integer Solvers like below
into PAGMO (maybe in next GSOC)

https://developers.google.com/optimization/mip/integer_opt
http://scip.zib.de/#about
https://www.gnu.org/software/glpk/

**Comment by darioizzo** [comment]
Sure. I think sga is able at the moment to tackle mixint ...

**Comment by bluescarni** [comment]
@arita37 do you mind if I keep this open as a reminder? Porting of IHS to pagmo2 is on the roadmap.

**Comment by bluescarni** [comment]
This was implemented in #141 and it will be part of the next pagmo release.

**Comment by arita37** [comment]
congratulation....

On Dec 29, 2017, at 1:53, Francesco Biscani <notifications@github.com> wrote:

This was implemented in #141 and it will be part of the next pagmo release.

―
