### ISSUE TITLE
Pagmo Installation test code

### ISSUE THREAD

**Issue by SBTheta** [esa/pagmo2#127]
Hello,

I am trying to run the quickstart test code for pagmo2. First where should the test cpp file be located ? I am getting errors that it cannot find "pagmo/pagmo.hpp" and "pagmo/config.hpp" files.

SB

**Comment by darioizzo** [comment]
Did you install the pagmo headers and make them available to your compiler? The location of the file test cpp is irrelevant.

I am closing this as it's not an issue, but a support request that should be raised on gitter instead.
