### ISSUE TITLE
NSGA II not dealing correctly with negative integers

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#137]
The algorithm nsga ii on the line:
https://github.com/esa/pagmo2/blob/master/include/pagmo/algorithms/nsga2.hpp#L539

mutates an integer decision vector component within its bounds, but it casts them to unsigned int, thus creating overflows or UBs when the bounds contain negative values (which is allowed in pagmo)

**Comment by darioizzo** [comment]
https://github.com/esa/pagmo2/blob/master/include/pagmo/algorithms/nsga2.hpp#L537 this should also be corrected to <0 not <=0

**Comment by bluescarni** [comment]
@darioizzo we can close this I imagine?

**Comment by darioizzo** [comment]
yeps.
