### ISSUE TITLE
Installation Error, boost libraries too old. How to point `ccmake` to the new libraries?

### ISSUE THREAD

**Issue by ppau1** [esa/pagmo2#150]
### Problem:

I'm trying to install PyGMO on Linux Red Hat 5 following the instructions in the official site. 

When running the `ccmake ../` command I get an error telling me that my Boost libraries are too old: 

     CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1111 (message):
       Unable to find the requested Boost libraries.
    
       Boost version: 1.41.0
    
       Boost include path: /usr/include
    
       Detected version of Boost is too old.  Requested version was 1.48 (or
       newer).
     Call Stack (most recent call first):
       CMakeLists.txt:99 (FIND_PACKAGE)
    
    
    
     CMake Error at CMakeLists.txt:116 (MESSAGE):
       I cannot find the keplerian_toolbox library or headers, please install it
       and make sure it can be found

I then installed Boost 1.48 using `sudo yum install boost148-devel` without problems. Now, my `usr/lib64` directory has both copies of the 1.41 and 1.48 versions of the different lib files:

```bash
    ▶ ls -l | grep boost | head -n 20
    drwxr-xr-x  2 root root     4096 Feb 21 20:11 boost
    drwxr-xr-x  2 root root     4096 Feb 21 21:40 boost148
    -rwxr-xr-x  1 root root    32536 Apr 17  2015 libboost_chrono-mt.so.1.48.0
    -rwxr-xr-x  1 root root    32504 Apr 17  2015 libboost_chrono.so.1.48.0
    lrwxrwxrwx  1 root root       31 Feb 21 20:11 libboost_date_time-mt.so -> libboost_date_time-mt.so.1.41.0
    -rwxr-xr-x  1 root root    75664 Feb  8  2012 libboost_date_time-mt.so.1.41.0
    -rwxr-xr-x  1 root root    67168 Apr 17  2015 libboost_date_time-mt.so.1.48.0
    lrwxrwxrwx  1 root root       28 Feb 21 20:11 libboost_date_time.so -> libboost_date_time.so.1.41.0
    -rwxr-xr-x  1 root root    75560 Feb  8  2012 libboost_date_time.so.1.41.0
    -rwxr-xr-x  1 root root    67064 Apr 17  2015 libboost_date_time.so.1.48.0
    lrwxrwxrwx  1 root root       32 Feb 21 20:11 libboost_filesystem-mt.so -> libboost_filesystem-mt.so.1.41.0
    -rwxr-xr-x  1 root root    87624 Feb  8  2012 libboost_filesystem-mt.so.1.41.0
    -rwxr-xr-x  1 root root   124488 Apr 17  2015 libboost_filesystem-mt.so.1.48.0
    -rwxr-xr-x  1 root root    87616 Feb 18  2012 libboost_filesystem-mt.so.5
    lrwxrwxrwx  1 root root       29 Feb 21 20:11 libboost_filesystem.so -> libboost_filesystem.so.1.41.0
    -rwxr-xr-x  1 root root    87584 Feb  8  2012 libboost_filesystem.so.1.41.0
    -rwxr-xr-x  1 root root   124448 Apr 17  2015 libboost_filesystem.so.1.48.0
    -rwxr-xr-x  1 root root    87584 Feb 18  2012 libboost_filesystem.so.5
    lrwxrwxrwx  1 root root       27 Feb 21 20:11 libboost_graph-mt.so -> libboost_graph-mt.so.1.41.0
    -rwxr-xr-x  1 root root   171632 Feb  8  2012 libboost_graph-mt.so.1.41.0
```

But even now I still get the same error when running the `ccmake` command.

### Question:

How can I tell PyGMO to look for the boost 1.48 libraries?

**Comment by darioizzo** [comment]
Am I correct you are trying to install the old Pagmo 1.x code? I say so as I see a keplerian toolbox headers search which is weird. 
Pagmo 1.x is no longer supported. 
You should switch to pagmo2 and pykep2 (keplerian toolbox). They are now (since a few years) disentangled projects. They can also be installed via conda or pip, no need to compile locally (for most cases).

**Comment by ppau1** [comment]
You're absolutely right! It might be that I was too tired yesterday when I tried this, but may I suggest to make it more explicitly clear in the documentation of pagmo1 to install pagmo2 instead, and that there is an easy conda/pip installation available?

Excited to try Pagmo on some hard problems! Thanks!

**Comment by darioizzo** [comment]
In the old pagmo github pages (https://github.com/esa/pagmo) pagmo2 is well visible in the First paragraph of the readme docs. 

Where would you have liked to be warned about pagmo2?

**Comment by ppau1** [comment]
I started from here: http://esa.github.io/pygmo/ and clicked on the installation instructions. At no point in the process it is said that one should install pagmo2 instead.
