### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#166]
Will park here some typos in the docs that we can fix in a dedicated commit when accumulated. 
- [x] Island Tutorial: https://esa.github.io/pagmo2/docs/python/tutorials/using_island.html ("run evolutions ona separate thread" -> on a)
- [x] https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_simple.html. 1) That easy! -> That's easy! 2) oops -> Oops
- [x] Island Tutorial: bith->both, acquinted-> acquainted
- [x] IHS documentation says: "The original IHS algorithm was designed to solve unconstrained, deterministic single objective problems. In pygmo, the algorithm was modified to tackle also multi-objective, constrained (box and non linearly). Such extension is original with pygmo." which is confusing as multiobjective and constrained problems cannot be solved together.

**Comment by KishManani** [comment]
- [ ] "there introduced." -> "introduced there." or for greater clarity "introduced in the paper." https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_constrained.html

**Comment by ampatzia** [comment]
- [ ]  "Improved Harmony Serach" -> "Improved Harmony Search"   in Heuristic Global optimization table , collumn common names https://esa.github.io/pagmo2/docs/algorithm_list.html

**Comment by bluescarni** [comment]
- [ ] a math formatting error at the beginning of the multiobjective UDP python tutorial: https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_multi_objective.html

**Comment by bluescarni** [comment]
Fixed in #198.
