### ISSUE TITLE
How to set an initial parameter guess in NLOpt interface?

### ISSUE THREAD

**Issue by paupereira** [esa/pagmo2#168]
**Description of the problem:**
I'm using Pygmo to solve a non-linear optimization problem with it's NLOpt interface. 
I discovered that I can set NLOpt options using something like `algo.extract(pg.nlopt).ftol_rel = 1e-8`.
But I can't find a way to set the initial parameter guess. It seems that Pygmo is choosing a random starting point from within the bounds I gave to the parameter space.

The NLOpt documentation has the following relevant [example](https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/):

```C
double x[2] = { 1.234, 5.678 };  /* `*`some` `initial` `guess`*` */
double minf; /* `*`the` `minimum` `objective` `value,` `upon` `return`*` */
if (nlopt_optimize(opt, x, &minf) < 0) {
    printf("nlopt failed!\n");
}
else {
    printf("found minimum at f(%g,%g) = %0.10g\n", x[0], x[1], minf);
}
```

**Question:**
Is there a way to set an initial parameter guess in NLOpt interface?

**Comment by darioizzo** [comment]
Please do not open issues on usage questions. We have a dedicated chat on gitter for that. Post your questions there: https://gitter.im/pagmo2/Lobby
I will answer this here and close the issue, but refer to gitter in the future.

You set the initial guess manually by defining a population as follows:
```
using pagmo;
algorithm algo{nlopt{CONSTRUCT_ME}};
problem prob{my_prob{CONSTRUCT_ME}};
vector_double ig{1.234, 5.678};
population pop(prob);
pop.push_back(ig);
pop = algo.evolve(pop);
```
