### ISSUE TITLE
Is it possible to kill the archipelago processes after completion?

### ISSUE THREAD

**Issue by bsugerman** [esa/pagmo2#171]
I'm running pygmo in Anaconda on windows. After I'm done running an archipelago, all the python processes that it opened remain idle and only die if I quit the python interpreter. Is there a hidden way to shut the archipelago processes down once I'm done using them? Or can this be added as a feature, i.e. `archi.close()`?

**Comment by bsugerman** [comment]
I think that exposing the multiprocessing `close()` and `join()` is a very useful feature. I'm finding extremely erratic behavior in my archipelago behavior because so many python threads are left running after the archipelago has finished. Although I suppose I should ask whether the current version uses `multiprocessing` or another method to run islands in parallel.

**Comment by bluescarni** [comment]
@bsugerman Sorry I initially missed the first part of our reply. What do you mean by "extremely erratic behaviour" exactly?

By default on Windows the current pygmo version uses ``multiprocessing`` if the algorithm or the problem are implemented in Python. If both the algorithm and the problem are implemented in C++, it will use multithreading.

**Comment by bluescarni** [comment]
@bsugerman There's an implementation of this functionality up at #187.

**Comment by bluescarni** [comment]
#187 has now been merged to master (which will soon become pagmo 2.8). I'll close this issue report.
