### ISSUE TITLE
undefined reference to "pagmo::hypervolume::get_best_compute"

### ISSUE THREAD

**Issue by mofeilu** [esa/pagmo2#172]
Hi,  I have installed pagmo2 and trying to use its hypervolume calculation routines.  
I found that "pagmo::hypervolume::get_best_compute" only have declaration in .hpp file but is not defined. I could not find any .cpp file that define the behavior of "get_best_compute" .  Could anyone help to check on this issue?   Thanks in advanced!

**Comment by darioizzo** [comment]
pagmo2 is a header only library, you will not find any cpp files. From the pagmo files:

```
    // Choose the best algorithm to compute the hypervolume the actual implementation is given
    // in another headers as to not create a circular dependency problem
    std::shared_ptr<hv_algorithm> get_best_compute(const vector_double &r_point) const;
```

The actual implementation is in ```hv_hv3d.hpp``` and is:

```
/// Chooses the best algorithm to compute the hypervolume
/**
* Returns the best method for given hypervolume computation problem.
* As of yet, only the dimension size is taken into account.
*
* @param r_point reference point for the vector of points
*
* @return an std::shared_ptr to the selected algorithm
*/
inline std::shared_ptr<hv_algorithm> hypervolume::get_best_compute(const vector_double &r_point) const
{
    auto fdim = r_point.size();

    if (fdim == 2u) {
        return hv2d().clone();
    } else if (fdim == 3u) {
        return hv3d().clone();
    } else {
        return hvwfg().clone();
    }
}
```

**Comment by mofeilu** [comment]
Hi darioizzo,
Thank you very much for your quick reply,  
in hv_hv3d.hpp  **get_best_compute** is implemented, but that is for **class hv3d**,  I do not understand how does that work for the member function of **class hypervolume**

Anyway, I prepared my minimum example like below:

----------------------------------------------------------------------------------
#include <vector>
#include <pagmo/utils/hypervolume.hpp> // for pagmo2

using namespace std;
int main(int argc, char** argv)
{

 std::vector<std::vector<double> > X = {{0.5,0.5}, {0.1,0.3}};
 pagmo::hypervolume hv(X);  // this is pagmo2 routine

 std::vector<double> refPt = {0.7, 0.7};
 double t = hv.compute(refPt);
}
-------------------------------------------------------------------------------------
I compile it
g++ main.cpp -g -I$PAGMO_INC -I$EIGEN_INC -lpthread -o main -std=c++11
and got the following error:

/tmp/ccWWZaZ1.o: In function `pagmo::hypervolume::compute(std::vector<double, std::allocator<double> > const&) const':
/user/libsync/RHEL6/polaris/POP/libs/pagmo2/include/pagmo/utils/hypervolume.hpp:284: undefined reference to `pagmo::hypervolume::get_best_compute(std::vector<double, std::allocator<double> > const&) const'
collect2: error: ld returned 1 exit status

**Comment by darioizzo** [comment]
Thanks for the report. The hypervolume part of pagmo is a port of old code from pagmo 1.x and its header logic is messed up and not documented, so you are right to be confused. Add these headers to your main and it will compile. We may have to provide a utility header that makes this easier .... Let me know if your problem is solved.
```
#include <pagmo/utils/hv_algos/hv_algorithm.hpp>
#include <pagmo/utils/hv_algos/hv_bf_approx.hpp>
#include <pagmo/utils/hv_algos/hv_bf_fpras.hpp>
#include <pagmo/utils/hv_algos/hv_hv2d.hpp>
#include <pagmo/utils/hv_algos/hv_hv3d.hpp>
#include <pagmo/utils/hv_algos/hv_hvwfg.hpp>
#include <pagmo/utils/hypervolume.hpp>
```

**Comment by mofeilu** [comment]
Thank you for the reply!  Problem is solved.
As you suggested,  providing a utility header will definitely be helpful, please consider that.
