### ISSUE TITLE
Support Lexicographic preferences

### ISSUE THREAD

**Issue by ObadaJabassini** [esa/pagmo2#174]
Hello
I am trying to optimize a multiobjective problem, does pygmo support Lexicographic method? And if not, is there a package which solves this problem?

**Comment by darioizzo** [comment]
What do you exactly intend with lexicographic method?

**Comment by darioizzo** [comment]
will close this. Please ask question on the pagmo gitter channel (https://gitter.im/pagmo2/Lobby) rather than opening issues here. Thanks.

**Comment by ObadaJabassini** [comment]
I am trying to implement a behaviour based fuzzy robot, every component gives a function, there are three components: obstacle avoidance, goal reaching ,and  local minimum escape.
Obviously this is a moo problem, but there are some preferences here, obstacle avoidance is more preferable than goal reaching so the correct method to solve this problem is lexiographic ordering
