### ISSUE TITLE
c++ document

### ISSUE THREAD

**Issue by thanhchuong8252** [esa/pagmo2#175]
hello,

i am going to use pagmo2 in mechanical-structure optimization (combine with finite element method)., and pagmo2 simply a good package for large-scale, parallel programming...

do you have any document for c++ that similar to python document..? i am new user to c++, and it will help me to study pagmo2

thank you very much,

**Comment by darioizzo** [comment]
please use our gitter channel for these questions, do not open issues in github.
gitter -> https://gitter.im/pagmo2/Lobby

docs (also c++) are here: https://esa.github.io/pagmo2/
no c++ tutorial at the moment. We welcome PR on that.

**Comment by thanhchuong8252** [comment]
thank you very much
