### ISSUE TITLE
Parallelizing individual algorithms

### ISSUE THREAD

**Issue by tmpITK** [esa/pagmo2#177]
Hi! 

I'd like to ask if there is a straight-forward "pygmoish" way to parallelize the evaluation of candidate solutions in each generation for an algorithm (not islands). I haven't found anything about this in the documentation and we do not want to tinker with the source code if it can be avoided.

Thank you in advance!

**Comment by willcodeforfudd** [comment]
I'd second this.  Am looking at splitting fitness evaluation into 'call_fitness' and 'get_fitness' too.  This should be a fairly simple change, but it means working through the pagmo and pygmo apis.

see: https://github.com/esa/pagmo2/issues/143#issuecomment-439711328

**Comment by bluescarni** [comment]
The batch fitness evaluation framework (which includes the parallelisation of some algorithms) has now been completed on the Python side with the release of pagmo 2.13. I will close this report.
