### ISSUE TITLE
Adding more variables to NSGA ii

### ISSUE THREAD

**Issue by wpriyadarshani** [esa/pagmo2#178]
I am working on the NSGA II algorithm. I want to know with the pagmo2 can I add more than one variable to the chromosome. For example, can I represents the width and height of the image using the chromosome in this algorithm?

**Comment by darioizzo** [comment]
Please do not open issues on github for user questions.
The gitter chat (https://gitter.im/pagmo2/Lobby) is where you can ask for support to the community.

 A short answer to your question is: yes. pagmo deals with multimodal problems.
