### ISSUE TITLE
mp_island ignores poolsize?

### ISSUE THREAD

**Issue by jakobj** [esa/pagmo2#193]
I am trying to parallelize the evaluation of the fitness function via an island object. The following toy example demonstrates my problem:
```python
import os
import sys
import time

sys.path.insert(0, os.path.expanduser('~/opt/pagmo2/install/lib/python3.6/site-packages/'))
import pygmo as pg

SEED = 1234


class loss():

    def fitness(self, genome):

        time.sleep(0.05)
        f = (genome[0] - 5.) ** 2
        return [f]

    def get_bounds(self):
        return ([0.], [1.])


if __name__ == '__main__':

    poolsize = int(sys.argv[1])

    algo = pg.algorithm(pg.xnes(gen=50, memory=True, seed=SEED))
    prob = pg.problem(loss())
    pop = pg.population(prob, size=5, seed=SEED)

    udi = pg.mp_island()
    udi.resize_pool(poolsize)
    isl = pg.island(algo=algo, pop=pop, udi=udi)

    t = time.time()
    isl.evolve()
    print(isl)
    isl.wait()

    print('took {:.3f}s'.format(time.time() - t))

```
Independent of the poolsize (which is passed as a commandline argument), the `evolve` call takes the same time to return. I would have expected that at least up to 4 processes I would see a linear speedup on my machine. Am I misunderstanding the concept of the processes pool of an island?

ps: this might be related to #177?

**Comment by bluescarni** [comment]
The parallelisation model in pagmo is coarse-grained, meaning that you can run multiple optimisations in parallel but not multiple indivdual objfun evaluations in parallel within the same optimisation run.

In other words, you can construct multiple islands and evolve them in parallel, but you cannot obtain any form of parallelism within a single island using pagmo (of course you are free to parallelise the implementation of your own problem/algorithm as you please).

The preferred way of managing multiple islands in pagmo/pygmo is via the archipelago class, you can see a python tutorial here:

https://esa.github.io/pagmo2/docs/python/tutorials/using_archipelago.html

Once the archipelago topology/migration functionality is implemented, the islands in the archipelago will gain the ability of exchanging individuals during the optimisation process (but that doesn't change the fundamentally coarse parallelisation model, it will "just" improve convergence).

**Comment by jakobj** [comment]
OK, thank you for your quick answer and your explanation. Since a single evaluation of the fitness is actually quite expensive in our case, we really need the fine grained parallelism. If I understand you correctly, there is no conceptual issue with parallelizing the algorithm. We could hence have xnes spin up a single process per fitness evaluation? If this in possible in general, I will look into building a parallel version of xnes.

**Comment by bluescarni** [comment]
You can certainly code an algorithm that takes advantage of some form of parallelism within its ``evolve()`` method (e.g., if your algorithm needs to evaluate independent decision vectors you can certainly delegate the computation of the objfun to a separate thread or process). This will not impact pagmo, as all pagmo sees is a black box with an evolve method that returns an optimised population, what happens inside the evolve method is of no concern to pagmo.

That said, the question of finer-grained parallelism comes up fairly often, so we might end up doing something about it in pagmo eventually. No concrete plans yet though.

**Comment by jakobj** [comment]
Great, thanks for the info! I'll look into it. You can close this issue unless you want to keep it around for future reference.
