### ISSUE TITLE
Archipielago Runtime Error with Toy_Problem Pygmo Example

### ISSUE THREAD

**Issue by martincarcamo** [esa/pagmo2#199]
I was trying to calibrate through the archipielago pygmo class, nonetheless, the code raised the following error:

 
```
RuntimeError: 

        An attempt has been made to start a new process before the
```
 

According to several threats on Stackoverflow, and the same Exception error in the Multiprocessing Class, it is advised to add the following in the main module:

 
```
if __name__ == '__main__':
```
 

Nonetheless, despite many attempts I still can’t solve this. I have even tried with the toy_problem example on the pygmo web page (https://esa.github.io/pagmo2/docs/python/tutorials/using_archipelago.html), but the same error occurs. 

I found a similar problem published in Issue#106 (https://github.com/esa/pagmo2/issues/106) but it has been closed and fixed.

I was wondering if anyone else had the same problem and you could help me with the solution 

In advance thanks!

**Comment by bluescarni** [comment]
Can you post the full error message and the stacktrace? It would also help to know exactly what sequence of operations you are doing and/or, if possible, a minimally small piece of code that reproduces the issue you are seeing.

We run a fairly extensive test suite in our continuous integration system, so I am a bit surprised to see that there are issues with the toy problem from the docs. Maybe you can also describe your setup (e.g., platform, python version, etc.).

**Comment by martincarcamo** [comment]
Hi Bluescarni, thank you very much for your reply. 

Sure, find below the two files, error message and setup. 

FILE#1: UDP_NSGA2.py

class toy_problem:
     def __init__(self, dim):
         self.dim = dim

     def fitness(self, x):
         return [sum(x), 1 - sum(x*x), - sum(x)]

     def gradient(self, x):
         return pg.estimate_gradient(lambda x: self.fitness(x), x) # numerical gradient

     def get_nec(self):
         return 1

     def get_nic(self):
         return 1

     def get_bounds(self):
         return ([-1] * self.dim, [1] * self.dim)

     def get_name(self):
         return "A toy problem"

     def get_extra_info(self):
         return "\tDimensions: " + str(self.dim)

FILE#2: NSGA2_pygmo.py

import pygmo as pg
from UDP_NSGA2 import toy_problem
a_cstrs_sa = pg.algorithm(pg.cstrs_self_adaptive(iters=1000))
p_toy = pg.problem(toy_problem(50))
p_toy.c_tol = [1e-4, 1e-4]
archi = pg.archipelago(n=32,algo=a_cstrs_sa, prob=p_toy, pop_size=70)
print(archi)
archi.get_champions_f()
archi.evolve()
print(archi)
archi.wait()
archi.get_champions_f()

The Error Message I get is the following: 
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

I am using JetBrains, with Anaconda3 and Python 3.6 on a Windows 10, 64 bit 2 cores. 

In advance thank you very much!

**Comment by darioizzo** [comment]
Can you tell us how the error is raised?
Are you typing
```
python NSGA2_pygmo.py
```
from a shell or are you importing the script from an ipython session?
```
import NSFA2_pygmo 
```
or something else?

**Comment by bluescarni** [comment]
If you are running ``NSGA2_pygmo.py`` as a script, as in ``python NSGA2_pygmo.py``, you will need to place your code in an ``if __name__ == "__main__":`` guard:

```python

        import pygmo as pg
        from UDP_NSGA2 import toy_problem
        a_cstrs_sa = pg.algorithm(pg.cstrs_self_adaptive(iters=1000))
        p_toy = pg.problem(toy_problem(50))
        ...
```

The reason is that the archipelago is internally using the python multiprocessing module, which will try to "import" the script which is creating the archipelago. Without the ``if __name__ == "__main__":`` guard, each child process would try to spawn an archipelago upon import, which would end up creating more processes recursively.

**Comment by martincarcamo** [comment]
Thank you so much! It now works perfectly! Amazing software, congratulations!
