### ISSUE TITLE
Automating Mixed Integer Optimisation in Pygmo 2

### ISSUE THREAD

**Issue by Gapaches** [esa/pagmo2#200]
The example in Pygmo 'Coding a User Defined Problem with an integer part (MINLP)' (https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_minlp.html) sets the integer decision variables manually to 1 or 0 in the final step. Having too many decision variables to do this manually, how can this be automated? Any good examples? Many thanks in advance

**Comment by darioizzo** [comment]
this looks more as a python related question than an issue with pagmo. 
Maybe you can ask for support on our gitter channel? (https://gitter.im/pagmo2/Lobby)
