### ISSUE TITLE
Pygmo simulated annealing not working

### ISSUE THREAD

**Issue by ampatzia** [esa/pagmo2#201]
While trying to solve using the simulated annealing algorithm,
```
import pygmo as pg
unew = pg.ackley(dim = 2)
pop = pg.population(unew, size=200)
algo = pg.algorithm(pg.simulated_annealing(gen=100))
```
 the following error occurred: 
```
"algo = pg.algorithm(pg.simulated_annealing(gen=100))

ArgumentError: Python argument types in
    simulated_annealing.__init__(simulated_annealing)
did not match C++ signature:
    __init__(_object*, double Ts=10.0, double Tf=0.1, unsigned int n_T_adj=10, unsigned int n_range_adj=10, unsigned int bin_size=10, double start_range=1.0, unsigned int seed)
    __init__(_object*, double Ts=10.0, double Tf=0.1, unsigned int n_T_adj=10, unsigned int n_range_adj=1, unsigned int bin_size=20, double start_range=1.0)
    __init__(_object*)"
```
I don't thinh it matters but this was run using spyder with python 3.6 in windows.

**Comment by darioizzo** [comment]
Please do not open issues on syntax errors if you are unsure whether its your or pagmo's fault. First ask on gitter: https://gitter.im/pagmo2/Lobby

Also, please first read the docs before asking questions: https://esa.github.io/pagmo2/docs/python/algorithms/py_algorithms.html#pygmo.simulated_annealing

You can see in the docs that ```gen``` is not a kwarg for simulated annealing.
