### ISSUE TITLE
Benchmarking efficiently using hypervolume to function evaluation plots

### ISSUE THREAD

**Issue by bicep** [esa/pagmo2#209]
Hello,

I am trying to benchmark several algorithms in pygmo by using hypervolume to function evaluation plots. This is what I have produced so far:

![benchmark](https://user-images.githubusercontent.com/11747211/44207366-82b38b00-a18f-11e8-8b31-cf7889c68d39.png)

 The way I do it now is inefficient: I run a for loop, each time calling the algorithm with a different generation argument all the way to 30 generations. Something like this for moead:
```
GENERATIONS = 30

for i in range(GENERATIONS):
    MOEAD_ALGO = pg.algorithm(pg.moead(gen=i))
   # evolve happens inside this function call
    (MOEAD_HYPERVOLUME, MOEAD_FUNCTION_EVALS) = run_algo_return_plot_data(MOEAD_ALGO, POPULATION)
    MOEAD_HV_VALUES.append(MOEAD_HYPERVOLUME)
    MOEAD_FEVAL_VALUES.append(MOEAD_FUNCTION_EVALS)
```
I want a way to be able to get this plot in a single evolve function call. I'm not sure if Pygmo accommodates for this, but I was thinking if it doesn't, the best way would be for me to know the arguments passed to the problem's fitness function, and the return value of that fitness function.

This way, I can store the return value in some kind of array, and then manually construct a population for every subsequent n elements in the array (where n is the size of the population) and then the hypervolume for each function evaluation count, while only having to run the evolve function once.

Does this make sense? Is there a way for me to do this or is there a better approach?

**Comment by CoolRunning** [comment]
Hi,

so why don't you do something like this?



```python
import pygmo as pg
import matplotlib.pyplot as plt
```


```python
uda_moead = pg.algorithm(pg.moead(gen=1))
uda_nsga2 = pg.algorithm(pg.nsga2(gen=1))
udp = pg.problem(pg.problems.dtlz(2, dim=20, fdim=6))
```


```python
# same (random) starting population for both algos
pop_moead = pg.population(udp, 56)
pop_nsga2 = pop_moead
hv = pg.hypervolume(pop_moead)
ref = hv.refpoint(offset=4.0)
start_hv = hv.compute(ref)
```


```python
max_gen = 20
fevals = [(pop_moead.problem.get_fevals(), pop_nsga2.problem.get_fevals())]
hvs = [(start_hv, start_hv)]
for i in range(max_gen):
    pop_moead = uda_moead.evolve(pop_moead)
    pop_nsga2 = uda_nsga2.evolve(pop_nsga2)
    hv_moead, hv_nsga2 = pg.hypervolume(pop_moead), pg.hypervolume(pop_nsga2)
    
    #note that our reference point needs to be fixed
    hvs.append( (hv_moead.compute(ref), hv_nsga2.compute(ref)) )
    fevals.append( (pop_moead.problem.get_fevals(), pop_nsga2.problem.get_fevals()) )
```


```python
fig, ax = plt.subplots()
ax.plot(fevals, hvs, marker='x', ls='None')
ax.set_xlabel('function evaluations')
ax.set_ylabel('hypervolume')
ax.legend(['MOEAD', 'NSGAII'])
ax.grid()
```
![output_4_0](https://user-images.githubusercontent.com/925528/44209881-11f77900-a165-11e8-89d4-b1cd1dc94515.png)

**Comment by bicep** [comment]
Awesome, thank you!
