### ISSUE TITLE
How to provide an initial guess when using nlopt  "slsqp"

### ISSUE THREAD

**Issue by hashem65** [esa/pagmo2#212]
Hi All

In my optimisation solver, first of all the global optimiser solves and brings a rough answer for me. However, it is very crazy in refining the final answer when it is close to it, 
I would like to pass its answer to the local optimiser which uses the gradient and refines it faster. 
Couldn't find finally how and where to provide the initial guess, which is the output of the my global solver. 
Pygmo doesn't work like PyOpt or .... in this case.... 

class GrowthOptimization(object):
         def __init__(self):
                  ....
         def fitness(self,x):
                   .....
         def gradient(self, x):
                  ......
         def get_bounds(self):
                  return ([-0.2]*36,[0.25]*36)

 

if __name__ == '__main__':
    gp = GrowthOptimization()
    nl = pg.nlopt('slsqp')
    prob = pg.problem(gp)
    algo = pg.algorithm(nl)
    pop = pg.population(prob,20)
    print(dir(pop))
    pop = algo.evolve(pop)

print(pop.champion_f)

**Comment by bluescarni** [comment]
After you have tun the global optimiser, you can start another optimisation with the local optimizer (nlopt). Just make sure that you evolve the population that resulted from the global optimisation. In the code you pasted above, it looks like you are starting with a new population (which will have its individuals randomly chosen upon creation).

**Comment by hashem65** [comment]
Hi, Thanks for the reply. 
Yes, I turn off the global and start the local optimiser. 
As I do not know how to add the initial guess, am  starting with a new population (which will have its individuals randomly chosen upon creation). The point you said what exactly my question. How to pass an initial guess to the NLopt optimization solver?

**Comment by bluescarni** [comment]
You can create a population and fill it up with any decision vector you like. See the tutorial here, for instance:

https://esa.github.io/pagmo2/docs/python/tutorials/using_population.html

See also the full API docs for the population class:

https://esa.github.io/pagmo2/docs/python/py_population.html#pygmo.population

**Comment by bluescarni** [comment]
@hashem65 I'll go ahead and close this report, as I believe the docs I linked above contain the necessary information for understanding how to set the initial guesses. If you have more questions, please ask in the pagmo2 chat: https://gitter.im/pagmo2/Lobby
