### ISSUE TITLE
Meta-Optimization

### ISSUE THREAD

**Issue by Hvass-Labs** [esa/pagmo2#214]
I have used Pygmo in two small projects I just did on what I call Meta-Optimization. It is an idea that is closely related to Hyper-Parameter Optimization if you are familiar with that. We basically use one optimizer to tune the parameters of another optimizer. I think you might find this interesting and possibly even consider building support for it directly into Pygmo. The first project uses Pygmo in combination with scikit-optimize and the second project only uses Pygmo.

The source-code is available here:

https://github.com/Hvass-Labs/MetaOps

I made YouTube videos for the two projects here:

https://www.youtube.com/playlist?list=PL9Hr9sNUjfsl1877BS8m3yt8t_wq2IWji

I don't think I will be able to help you implement any of this in Pygmo, in part because I don't fully understand Pygmo, but also because I am self-employed and I have other things I need to work on. But I will be happy to answer any questions you might have, if you want to add some of these features to Pygmo - I think they would be really powerful features to have in Pygmo! However, I will not have regular internet access for at least several weeks, so it might be a while before I can answer your questions.

PS: I should perhaps say that I give some very mild criticism of some aspects of Pygmo in the videos. I hope you view that as constructive feedback.

**Comment by darioizzo** [comment]
Thanks for the links, interesting videos.

In pygmo we will be implementing a *racing* algorithm to tune optimizers parameters. Something on the lines of (http://esa.github.io/pygmo/tutorials/racing_algorithms.html) which was in pygmo 1.x

Your approach is also interesting, but it is not clear how it would generalize outside the particular problem instance you selected (rosenbrock dim 10) or how sensitive it is to the arbitrarily fixed meta fitnesses.

**Comment by Hvass-Labs** [comment]
Actually, I think it would be fairly straightforward to make a function `meta_optimize()` in Pygmo implemented entirely in Python similar to this:

https://github.com/Hvass-Labs/swarmops/blob/master/demo-meta-optimize.py

https://github.com/Hvass-Labs/swarmops/blob/master/swarmops/MetaOptimize.py

You could also let the user provide several "meta-fitness" functions to do multi-objective meta-optimization on either benchmark problems or their own problems. So the parameters can be tuned for multiple problems simultaneously, different run-lengths etc. It could actually be made very flexible and powerful using the existing pygmo implementation and just adding a little functionality.

When I worked on this maybe 10 years ago, I found that some people understood the idea very intuitively and others never saw the usefulness of meta-optimization. No matter how much I explained and demonstrated, they would rather spend days playing around with parameter settings manually. So I won't go into that long discussion again here :-)

I'll close this issue and perhaps sometime in the future someone else might reopen it and work on it.

**Comment by Hvass-Labs** [comment]
Here is an example of how to tune an optimizer's parameters for several benchmark problems. This is all written in Python using Pygmo, so it would be possible for you to include this as a feature that others could use directly when importing Pygmo:

https://github.com/Hvass-Labs/MetaOps/blob/master/03_Meta-Optimization_Using_Many_Problems.ipynb
