### ISSUE TITLE
pagmo installation with Homebrew

### ISSUE THREAD

**Issue by jslee02** [esa/pagmo2#215]
I submitted [Homebrew formula for pagmo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pagmo.rb). It would be great if the installation instruction with Homebrew is added to the [documentation](https://github.com/esa/pagmo2/blob/master/doc/sphinx/install.rst) as something like:
```shell
brew install pagmo
```

As a note, the dependency of ipopt is omitted for now because the formula for ipopt is missing in homebrew-core yet.

**Comment by darioizzo** [comment]
That is very good news! Thanks. I am not familiar with homebrew, what happens when we do a new release? Someone needs to update the formula?

**Comment by jslee02** [comment]
By the way, this is not an issue so feel free to close.

**Comment by darioizzo** [comment]
Will keep it opened up to when the package is in homebrew and our docs are updated.

**Comment by bluescarni** [comment]
@jslee02 thank you! I'll make sure to add this to the installation docs.

Any chance to have a pygmo package as well?

**Comment by jslee02** [comment]
I haven't made a Homebrew formula for a python package before but let me give it a try. :smile:

**Comment by bluescarni** [comment]
@jslee02 Sorry for taking this long, the doc bits are now in #243. Any news on the pygmo package?

**Comment by bluescarni** [comment]
The installation instructions for Homebrew are now in master, the online documentation is updated. I will close this for now, thanks @jslee02.

**Comment by bluescarni** [comment]
I see this in the logs:

```
-- Required Boost libraries: python27
CMake Error at /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.68.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python27

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  cmake_modules/PagmoFindBoost.cmake:22 (find_package)
  CMakeLists.txt:157 (include)
```

It seems like it is unable to locate the Boost Python libraries, although the Boost headers seem to be detected. So it could be that either Boost.Python was not installed (is it packaged separately from the rest of Boost in Homebrew?) or the library has a name other than ``libboost_python27``.
