### ISSUE TITLE
pagmo_export.cmake not found in Cygwin installation

### ISSUE THREAD

**Issue by astrophysaxist** [esa/pagmo2#216]
Hi, I've compiled pagmo2 successfully from source with Cygwin. I was able to test compiling the getting_started.cpp just fine. Now, I'm looking to install pygmo from source, but I've hit a snag I'm not sure how to troubleshoot. After updating the configuration of my cmake to build only pygmo, I get an error:

```
$ /usr/local/bin/cmake ..
-- System name: CYGWIN
-- The C++ compiler ID is: GNU
-- YACMA autodetected C++ flags: -fdiagnostics-color=auto;-ftemplate-depth=1024;-fvisibility-inlines-hidden;-fvisibility=hidden;-Wno-attributes
-- YACMA autodetected C++ debug flags: -Wall;-Wextra;-Wnon-virtual-dtor;-Wnoexcept;-Wlogical-op;-Wconversion;-Wdeprecated;-Wold-style-cast;-pedantic-errors;-Wdisabled-optimization;-ftemplate-backtrace-limit=0;-Wsuggest-attribute=pure;-Wsuggest-attribute=const;-Wsuggest-attribute=noreturn;-Wsuggest-attribute=format;-Wodr;-Wsuggest-final-types;-Wsuggest-final-methods;-Wsuggest-override;-Wshift-negative-value;-Wshift-overflow=2;-Wduplicated-cond;-Wnull-dereference;-Wno-maybe-uninitialized
-- Thread library: 
-- POSIX threads detected.
-- POSIX threads affinity extensions NOT detected.
-- The 'thread_local' keyword is supported.
-- Python modules do NOT require linking to the Python library.
-- Python interpreter: /usr/bin/python
-- Python interpreter version: 2.7.14
-- Python include dir: /usr/include/python2.7
-- Generic UNIX platform detected.
-- Python modules install path: lib/python2.7/site-packages
-- Required Boost libraries: 
-- Boost version: 1.68.0
-- Detected Boost version: 106800
-- Boost include dirs: /usr/local/include
CMake Error at build/pagmo-config.cmake:16 (include):
  include could not find load file:

    /home/me/pagmo2/build/pagmo_export.cmake
Call Stack (most recent call first):
  CMakeLists.txt:148 (find_package)


-- Required Boost libraries: python27
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   python27
-- Detected Boost version: 106800
-- Boost include dirs: /usr/local/include
-- Removing the '-fvisibility=hidden' flag for Boost.Python > 1.63.
-- Setting up the compilation of the Python module 'core'.
-- Setting up extra compiler flag '-fwrapv' for the Python module 'core'.
-- Python < 3 detected, setting up extra compiler flag '-fno-strict-aliasing' for the Python module 'core'.
-- Configuring incomplete, errors occurred!
See also "/home/me/pagmo2/build/CMakeFiles/CMakeOutput.log".
See also "/home/me/pagmo2/build/CMakeFiles/CMakeError.log".
```
When does this "pagmo_export.cmake" file get made? Or do I have to make this. It seems that's what's tripping up cmake. If it matters I'm using CMake version 3.12.1.

Best,

Greg

**Comment by darioizzo** [comment]
That file should mbe made when you make install pagmo (not pygmo).

He should also print on screen where the files are copied (after make install)

**Comment by astrophysaxist** [comment]
Aha, after running make install to install only pagmo, I see that the pagmo_export.cmake file is in my cmake/pagmo directory at the default install location.

```-- Up-to-date: /usr/local/lib/cmake/pagmo/pagmo_export.cmake
```
Is there a flag I'm not setting that's the cause of why the pygmo configuration isn't finding this file?

**Comment by darioizzo** [comment]
@bluescarni might know more on what is going on in cygwin,
the suggested installation setup is to define as CMAKE_INSTALL_PREFIX the directory ~/.local ... files will then be installed there and under most linux distribution they will be found .... (never tried in cygwin)

may I ask you why you are going through the trouble of installing manually and not using the binary packages we provide?

**Comment by bluescarni** [comment]
@astrophysaxist you can try two things. The first is, when configuring the pygmo build, to launch the cmake command with the ``-DCMAKE_PREFIX_PATH=/usr/local`` option. This should instruct CMake to go and look for pagmo's cmake files in ``/usr/local``.

The other option you can try to set during pygmo's configure phase is ``-Dpagmo_DIR=/usr/local/lib/cmake/pagmo/``, which should point CMake exactly to where the config files are.

Please make sure you erase cmake's caches when experimenting with these variables.

We don't do any testing on cygwin, so I would be curious to hear how it goes for you :)

**Comment by astrophysaxist** [comment]
@darioizzo I like to use the unix-like environment of Cygwin when I'm tied down to Windows machines for other reasons, but I guess I've been in the weeds enough with downloading/installing by source that it's not sooo much trouble these days usually.

@bluescarni , changing the pagmo_DIR did in fact work, and I was able to at least start running make install. It seems things halt at "Linking CXX shared module core.dll". I've narrowed it down to some undefined references to some python functions (solved by adding a -lpython2.7) and some functions from libraries needed for IPOpt (solved by adding -llapack -lblas -lm -ldl) to the linking line I found inside pagmo2/build/pygmo/CMakeFiles/core.dir/link.txt:

```
/usr/bin/c++.exe -O3 -DNDEBUG   -shared -Wl,--enable-auto-import -o core.dll -Wl,--major-image-version,0,--minor-image-version,0 CMakeFiles/core.dir/core.cpp.o CMakeFiles/core.dir/docstrings.cpp.o CMakeFiles/co
re.dir/expose_algorithms_0.cpp.o CMakeFiles/core.dir/expose_algorithms_1.cpp.o CMakeFiles/core.dir/expose_problems_0.cpp.o CMakeFiles/core.dir/expose_problems_1.cpp.o CMakeFiles/core.dir/expose_islands.cpp.o /u
sr/local/lib/libboost_python27.dll.a /usr/local/lib/libboost_python27.dll.a /usr/local/lib/libnlopt.dll.a /usr/local/lib/libipopt.a
```
The linking to make core.dll succeeds when I enter the following in the pagmo2/build/pygmo directory:
```
/usr/bin/c++.exe -O3 -DNDEBUG   -shared -Wl,--enable-auto-import -o core.dll -Wl,--major-image-version,0,--minor-image-version,0 CMakeFiles/core.dir/core.cpp.o CMakeFiles/core.dir/docstrings.cpp.o CMakeFiles/core.dir/expose_algorithms_0.cpp.o CMakeFiles/core.dir/expose_algorithms_1.cpp.o CMakeFiles/core.dir/expose_problems_0.cpp.o CMakeFiles/core.dir/expose_problems_1.cpp.o CMakeFiles/core.dir/expose_islands.cpp.o /usr/local/lib/libboost_python27.dll.a /usr/local/lib/libboost_python27.dll.a /usr/local/lib/libnlopt.dll.a /usr/local/lib/libipopt.a -lpython2.7 -llapack -lblas -lm -ldl
```

Re-running make install (after having to go back and correct the CMAKE_INSTALL_PREFIX), it moved all the files to the right directory, and I can import pygmo in python. And the getting started script seems to work!

```
$ python getting_started.py
[array([  1.13293754e-06]), array([  3.38190148e-07]), array([  2.88440788e-07]), array([ 236.87666942]), array([  7.43961209e-07]), array([  5.59357431e-07]), array([  1.07852611e-06]), array([ 118.43833486]), array([  8.56372935e-07]), array([ 118.43833617]), array([  3.63290383e-07]), array([  1.40839984e-06]), array([ 118.43833599]), array([ 118.43833486]), array([  3.10608812e-07]), array([ 118.4383357])]
```

I'm not sure if there was a way for me to have added those needed linking statements earlier in configuring, but it turned out ok. Thanks for the tips earlier; I'm excited to start using this tool!

**Comment by bluescarni** [comment]
Glad to hear that you made it work!

Regarding the extra linking required, I have a couple of comments:

- the need or not to link to the python dll is something that we have established experimentally on the various platforms that we support. I will change the heuristic in the build system to force the linking to the python dll on Cygwin, since your experience shows that this is necessary.

- In the build system, we look for the ipopt libraries but we do not look for the libraries upon which ipopt depends (in this case, apparently, BLAS/lapack). This is fine as long as the linker can deduce on its own that the ipopt libraries have other dependencies at link time, which is usually the case on linux/osx with dynamic libraries. In your case however it seems like you are linking to a *static* ipopt library, for which I presume the deduction of the dependency chain is not possible. The correct solution to this problem would be to look not only for ipopt but for its dependencies as well.

I will close this report for the time being, please re-open if further problems arise.
