### ISSUE TITLE
ImportError: Module use of python27.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by nking1994** [esa/pagmo2#224]
When attempting `import pygmo as pg` I get the above error, I'm using Spyder with Python 3.6.3; not sure what I can do about it since I'm new to Python, any help would be appreciated.

EDIT: (Corrected an error in main body)

**Comment by bluescarni** [comment]
I am closing this as it seems that the issue is a Python version mismatch. @nking1994 please re-open if needed.
