### ISSUE TITLE
How to use PyGMO with scikit learn estimator

### ISSUE THREAD

**Issue by aminevsaziz** [esa/pagmo2#225]
Well is there a possibility to use the optimizers that PyGMO provide to fine tune models like randomForest or SVM?

**Comment by darioizzo** [comment]
Yes but you need to write yourself the UDP, we do not provide helpers to interface with scikit.

**Comment by aminevsaziz** [comment]
@darioizzo.
1. What is UDP?
2. Can you give brief demonstration or even explanation that help create the interfaces between PyGMO and scikit learn.

**Comment by darioizzo** [comment]
There are plenty of examples on UDPs (user defined problems) in the
documentation. Please check
https://esa.github.io/pagmo2/docs/python/tutorials/python_tut.html

**Comment by darioizzo** [comment]
If you need help on pygmo use, please use the gitter channel.
