### ISSUE TITLE
SystemError: initialization of core raised unreported exception

### ISSUE THREAD

**Issue by chengdi123000** [esa/pagmo2#231]
Environment:

docker jupyter/scipy-notebook

I install pygmo using:
```shell
conda install pygmo
apt update
apt install libgfortran4  # or there is libgfortran.so.4 missing
```

test:
```python
>>> import pygmo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pygmo/__init__.py", line 38, in <module>
    from .core import *
SystemError: initialization of core raised unreported exception
```

**Comment by bluescarni** [comment]
Just to make sure I understood correctly, this is a docker image in Windows?

You should not need to install any extra package from ``apt-get`` if you are using a conda environment. Are you sure the conda environment is setup & activated correctly?

**Comment by bluescarni** [comment]
Closing this report for now for lack of feedback. Please re-open if needed.

**Comment by dustming** [comment]
I get the same error with python 3.7

**Comment by ipatrol** [comment]
Same issue with jupyter, python 3.6.8.

**Comment by bluescarni** [comment]
@dustming @ipatrol 

We need more information in order to be able to help. Are you both running pygmo in a Docker image in Windows? Or is your setup different from the one originally reported here? In such a case, please open new issue reports with more details.
