### ISSUE TITLE
collect2: error: ld terminated with signal 11 [Segmentation fault] when installing PaGMO 2.9

### ISSUE THREAD

**Issue by salvaba94** [esa/pagmo2#232]
Hi,
 
I am trying to install PaGMO 2.9 together with NLopt for use in a C++ project and I was having some problems on the way.

The system where I need to work and the related compiler and libraries are:

- Operating system: SLES 9
- GNU gcc/g++ compiler: version 4.8.1 with libstdc++.so.6
- Boost: version 1.58.0
- NLopt: version 2.5.0
- Eigen: version 3.3.4

The options I'm using with cmake (with the ccmake command) are:
![image](https://user-images.githubusercontent.com/44756404/48566343-deaabe80-e8fa-11e8-94b3-295d3519428f.png)

When I execute the makefile, the process terminates with the following error:

[ 61%] Linking CXX executable nlopt
collect2: error: ld terminated with signal 11 [Segmentation fault]
make[2]: *** [tests/nlopt] Error 1
make[2]: *** Deleting file `tests/nlopt'
make[1]: *** [tests/CMakeFiles/nlopt.dir/all] Error 2
make: *** [all] Error 2

If I set the PAGMO_WITH_NLOPT option to off, the process also terminates with an error:

[ 84%] Linking CXX executable sga
collect2: error: ld terminated with signal 11 [Segmentation fault]
make[2]: *** [tests/sga] Error 1
make[2]: *** Deleting file `tests/sga'
make[1]: *** [tests/CMakeFiles/sga.dir/all] Error 2
make: *** [all] Error 2

Do you know how this problem could be solved?

Thank you in advance!

Kind regards,
Salva

**Comment by bluescarni** [comment]
I am closing this as there's not much we can do about compiler bugs.

**Comment by salvaba94** [comment]
Sure. I fixed the bug updating binutils, and recompiling afterwards. 
Without tests it always compiles fine.
Thanks for your help!
