### ISSUE TITLE
How to make decision variables unique?

### ISSUE THREAD

**Issue by nconsulting** [esa/pagmo2#234]
Hi,

I have 9 decision variables of which the first 6 should all be unique. So [0 1 2 3 4 5] is a solution but not [0 0 1 2 3 5] nor is [0 1 2 1 3 4] ... How do I define this in C++?

Kind regards,

Nick

**Comment by bluescarni** [comment]
Pinging @darioizzo 

Can you implement this as a constraint? Or a penalty perhaps?

**Comment by nconsulting** [comment]
I was thinking of using constraints but going through the example problems provided with pagmo2, the inequality constraints are of the form g<=0, if there is a way to define an inequality constraints as g < 0, I could use a constraint. 

I could say: - abs(x[0] - x[1]) < 0

Can this be done?

**Comment by darioizzo** [comment]
Please do not open issues on optimization questions. These should be asked in the gitter chat where the whole community can answer and help in real time (https://gitter.im/pagmo2/Lobby). Open issues to report bugs in the code.

Anyway, inequality constraints are set to be g<=0 as you mentioned. In the case of integers if you want to obtain (say)  - abs(x[0] - x[1]) < 0, just write  - abs(x[0] - x[1]) + 1 <= 0

I will close this, in case you want more support please get in touch on gitter.
