### ISSUE TITLE
Variable mutation widths support

### ISSUE THREAD

**Issue by ogutty** [esa/pagmo2#236]
Hi, I've got a problem for which a variable-width mutation operator is required.
Specifically, this arises when using the "Safe Mutations" paradigm (in a nutshell, this entails
using the gradient of a NN's weights w.r.t. its outputs, rather than w.r.t. a user-provided loss function,
and mutating each weight differently, based on the output's sensitivity to it):
https://github.com/uber-research/safemutations

Any chance of allowing for such a mutation operator, or pointing me to the location in the code where I could implement this?  Thanks..!

**Comment by darioizzo** [comment]
In what algorithm exactly you would need an ad hoc mutation operator? 

If I understand what you are trying to do, you are mutating the weights on a NN using a genetic type of algorithm where the mutation width (random or normal, I guess) relates to the gradient of the network outputs w.r.t. the weight.

If thats the case I see two ways to do that in pygmo:
1) Define your own UDA (user defined algorithm). That would require coding the genetic algorithm yourself and having the mutation width depend on the said gradients at each generation.
2) If you want to use the UDAs shipped with pagmo (maybe the sga algorithm?) you would need to perform evolution for one generation at a time reinstantiating the sga algorithm setting the problems bounds accordingly (the width of mutation, when random, in sga is upperbound - lowerbound), see the code: https://github.com/esa/pagmo2/blob/master/include/pagmo/algorithms/sga.hpp#L682

 Let us know if this is what you were looking for.

Dario

**Comment by ogutty** [comment]
Thanks for the help, your understanding matches what I had in mind.
Indeed, I can use the sga algorithm and reinstantiate at each generation (with crossover disabled).
If I find myself defining my own UDA I'll get back to you with a pull request.
Cheers,
               - Omri
