### ISSUE TITLE
Creating a new population using `pg.population()` for simple Numba jitted problems is expensive

### ISSUE THREAD

**Issue by nsn88** [esa/pagmo2#238]
For inexpensive fitness functions that are Numba jitted, much of the optimization time is used by `pg.population()` to initialize the population. The fitness function used below is just an arbitrary one and is used only to illustrate the behavior.

    import time
    import numpy as np
    import pygmo as pg
    from numba import jit
    
    
    ngen = 200
    npop = 25
    
    def test_python(niter):
        class TestProblem(object):
            def fitness(self, x):
                f = 0
                for i in range(niter):
                    f = f + (x[0]**(i+1) + np.sum(x))
                return [f]
    
            def get_bounds(self):
                return ([-10,-10,-10], [10,10,10])
    
        time1 = time.time()
        algo = pg.algorithm(pg.sade(gen=ngen))
        testprob = pg.problem(TestProblem())
        
        time2 = time.time()
        pop = pg.population(prob=testprob, size=npop)
        
        time3 = time.time()
        pop = algo.evolve(pop)
        time4 = time.time()
        
        print('\ntest_python niter={}'.format(niter))
        print('Time taken : {:.4}s + {:.4}s + {:.4}s = {:.4}s'.\
              format(time2-time1, time3-time2, time4-time3, time4-time1))
        print('Champion x : {}'.format(pop.champion_x))
        print('Champion f : {}'.format(pop.champion_f))
    
    
    def test_numba(niter):
        class TestProblem(object):
            def fitness(self, x):
                return TestProblem._fitness(x)
    
            @jit(nopython=True)
            def _fitness(x):
                f = 0
                for i in range(niter):
                    f = f + (x[0]**(i+1) + np.sum(x))
                return [f]
    
            def get_bounds(self):
                return ([-10,-10,-10], [10,10,10])
    
        time1 = time.time()
        algo = pg.algorithm(pg.sade(gen=ngen))
        testprob = pg.problem(TestProblem())
        
        time2 = time.time()
        pop = pg.population(prob=testprob, size=npop)
        
        time3 = time.time()
        pop = algo.evolve(pop)
        time4 = time.time()
        
        print('\ntest_numba niter={}'.format(niter))
        print('Time taken : {:.4}s + {:.4}s + {:.4}s = {:.4}s'.\
              format(time2-time1, time3-time2, time4-time3, time4-time1))
        print('Champion x : {}'.format(pop.champion_x))
        print('Champion f : {}'.format(pop.champion_f))
    
    
    if __name__ == '__main__':
        test_python(3)
        test_numba(3)
        test_python(100)
        test_numba(100)

When run, gives the output:

```
test_python niter=3
Time taken : 0.0s + 0.001s + 0.107s = 0.108s
Champion x : [-10.          -9.99999993  -9.99999996]
Champion f : [-999.99999886]

test_numba niter=3
Time taken : 0.0s + 0.099s + 0.025s = 0.124s
Champion x : [-10.          -9.99999991  -9.99999997]
Champion f : [-999.9999989]

test_python niter=100
Time taken : 0.0s + 0.015s + 2.527s = 2.542s
Champion x : [ -1.00696567 -10.         -10.        ]
Champion f : [-2100.19382257]

test_numba niter=100
Time taken : 0.0s + 0.099s + 0.026s = 0.125s
Champion x : [-1.00695554 -9.99999999 -9.99999996]
Champion f : [-2100.19381768]
```

`test_numba`'s `algo.evolve(pop)` is orders of magnitude faster than that of `test_python` as expected, but time taken for `pop = pg.population(prob=testprob, size=npop)` in `test_numba` (99ms) is significantly higher than that of `test_python` (15ms). For fitness functions requiring several hundred iterations, `test_numba` will scale better, but for simpler problems `pg.population()` presents a significant bottleneck.

The test function used above is just an arbitrary one. I am working on a similar simple problem with a relatively cheap fitness evaluation. My old SADE code in Matlab takes around 60ms and was expecting Pygmo+Numba to bring it down to 10ms. As a workaround, instead of creating the initial pop using the built-in `pg.population()` for every run, I used `pop.set_x()` to randomly position the pop before each run.

```
def test_pop(niter):
    def _test_pop(pop=None):
        class TestProblem(object):
            def fitness(self, x):
                return TestProblem._fitness(x)
    
            @jit(nopython=True)
            def _fitness(x):
                f = 0
                for i in range(niter):
                    f = f + (x[0]**(i+1) + np.sum(x))
                return [f]
    
            def get_bounds(self):
                return ([-10,-10,-10], [10,10,10])
    
        time1 = time.time()
        algo = pg.algorithm(pg.sade(gen=ngen))
        testprob = pg.problem(TestProblem())
        
        time2 = time.time()
        if pop is None:
            pop = pg.population(prob=testprob, size=npop)
        
        time3 = time.time()
        pop = algo.evolve(pop)
        time4 = time.time()
        
        print('Time taken : {:.4}s + {:.4}s + {:.4}s = {:.4}s'.\
              format(time2-time1, time3-time2, time4-time3, time4-time1))
        return pop
    
    startTime = time.time()
    print('\ntest_pop niter={}, New pop every run'.format(niter))
    for i in range(10):
        _test_pop()
    print('\nTotal time taken = {:.4}s'.format(time.time()-startTime))
    
    startTime = time.time()
    print('\ntest_pop niter={}, Reinitialize pop every run'.format(niter))
    pop = _test_pop()
    for i in range(9):
        for i in range(len(pop)):
            pop.set_x(i, pop.random_decision_vector())
        _test_pop(pop)
    print('\nTotal time taken = {:.4}s'.format(time.time()-startTime))


if __name__ == '__main__':
    test_pop(3)
```

Output:

```
test_pop niter=3, New pop every run
Time taken : 0.0s + 0.139s + 0.025s = 0.164s
Time taken : 0.0s + 0.103s + 0.027s = 0.13s
Time taken : 0.001s + 0.114s + 0.026s = 0.141s
Time taken : 0.0s + 0.147s + 0.026s = 0.173s
Time taken : 0.0s + 0.114s + 0.027s = 0.141s
Time taken : 0.0s + 0.152s + 0.027s = 0.179s
Time taken : 0.001s + 0.177s + 0.028s = 0.206s
Time taken : 0.0s + 0.119s + 0.029s = 0.148s
Time taken : 0.0s + 0.14s + 0.027s = 0.167s
Time taken : 0.001s + 0.103s + 0.025s = 0.129s

Total time taken = 1.585s

test_pop niter=3, Reinitialize pop every run
Time taken : 0.0s + 0.105s + 0.027s = 0.132s
Time taken : 0.0s + 0.0s + 0.025s = 0.025s
Time taken : 0.001s + 0.0s + 0.027s = 0.028s
Time taken : 0.0s + 0.0s + 0.027s = 0.027s
Time taken : 0.0s + 0.0s + 0.029s = 0.029s
Time taken : 0.0s + 0.0s + 0.028s = 0.028s
Time taken : 0.0s + 0.0s + 0.024s = 0.024s
Time taken : 0.0s + 0.0s + 0.026s = 0.026s
Time taken : 0.0s + 0.0s + 0.027s = 0.027s
Time taken : 0.0s + 0.0s + 0.028s = 0.028s

Total time taken = 0.384s
```

So my questions are:
1. Is this behavior of `pg.population()` expected/normal?
2. Is there a better way to re-initialize an existing population?
2. Is this workaround valid?

**Comment by bluescarni** [comment]
I am not familiar with the numba internals, but my hunch here is that there is an overhead for the compilation of the jitted function (which happens during the population initialisation, where the fitness function is invoked the first time).

Could you try the following steps:

- define the jitted fitness function outside the problem as a free function in your module,
- implement the problem's fitness function in terms of this new free function,
- invoke at least once the jitted free function before running the test,

and report your findings?

**Comment by nsn88** [comment]
That worked like a charm!

I moved the jitted `_fitness()` function outside the class and now am seeing good performance.

```
test_pop niter=3, New pop every run
Time taken : 0.0s + 0.001s + 0.022s = 0.023s
Time taken : 0.0s + 0.0s + 0.024s = 0.024s
Time taken : 0.0s + 0.001s + 0.022s = 0.023s
Time taken : 0.0s + 0.001s + 0.025s = 0.026s
Time taken : 0.0s + 0.001s + 0.023s = 0.024s
Time taken : 0.0s + 0.0s + 0.021s = 0.021s
Time taken : 0.0s + 0.0s + 0.023s = 0.023s
Time taken : 0.0s + 0.0s + 0.023s = 0.023s
Time taken : 0.0s + 0.001s + 0.026s = 0.027s
Time taken : 0.0s + 0.001s + 0.022s = 0.023s

Total time taken = 0.24s

test_pop niter=3, Reinitialise pop every run
Time taken : 0.0s + 0.0s + 0.024s = 0.024s
Time taken : 0.0s + 0.0s + 0.024s = 0.024s
Time taken : 0.001s + 0.0s + 0.023s = 0.024s
Time taken : 0.0s + 0.0s + 0.023s = 0.023s
Time taken : 0.0s + 0.0s + 0.023s = 0.023s
Time taken : 0.001s + 0.0s + 0.024s = 0.025s
Time taken : 0.0s + 0.0s + 0.025s = 0.025s
Time taken : 0.001s + 0.0s + 0.027s = 0.028s
Time taken : 0.0s + 0.0s + 0.024s = 0.024s
Time taken : 0.001s + 0.0s + 0.024s = 0.025s

Total time taken = 0.249s
```

Thank you very much :+1:

**Comment by bluescarni** [comment]
Glad to hear it! Will close this.

**Comment by nsn88** [comment]
@bluescarni 

The use of Numba jitted function `_fitness()` within the problem class was taken from this [tutorial](https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_simple.html?highlight=numba#notes-on-computational-speed). Maybe a note on this behavior should be included as performance gain is the sole reason to use Numba.
