### ISSUE TITLE
Multi-objective optimization with PSO

### ISSUE THREAD

**Issue by maggiofrancesco** [esa/pagmo2#251]
Hi!

I'm interested in doing multi-objective optimization with PSO. Searching for a library I stumbled on Pagmo.
The old version of Pagmo includes the NSPSO, but I noticed that this one is not included in Pagmo2. Is that right?
Will multi-objective optimization approaches with PSO be available in the next future?

Thank you in advance!

**Comment by bluescarni** [comment]
I don't think there should be issues with adding back that algorithm. @darioizzo perhaps you can elaboratE?

**Comment by darioizzo** [comment]
No no issue, PR are welcome, otherwise we will do it at the next round of algorithms addition.

**Comment by bluescarni** [comment]
NSPSO is being ported to pagmo2 in #314.

**Comment by bluescarni** [comment]
#314 has been merged, and NSPSO will be part of the next release (pagmo 2.12). Closing the report.

**Comment by Tomalwo** [comment]
You might not want to hear it, but when are you planning to release 2.12?

**Comment by bluescarni** [comment]
We are working on it. The current holdup is that we are trying to improve the conda packages to make them more resilient to potential API/ABI issues when updating pagmo.

The pagmo/pygmo code itself is in good shape for release, so if you have the option you are welcome to use the current git version in the meantime.

**Comment by bluescarni** [comment]
@Tomalwo 2.12 has been released today.

**Comment by Tomalwo** [comment]
Thanks for the head's up!
