### ISSUE TITLE
Delay in problem initialization

### ISSUE THREAD

**Issue by pcko1** [esa/pagmo2#252]
Hi,

I am using PYGMO to minimize a custom fitness function that consists of a neural network. The input shape is `(128,1)` and the output is scalar (single objective). The evaluation time of the fitness function is approx **150ms**.
The algorithms that I have tested are `pg.artificial_bee_colony`, `pg.de` and `pg.pso` and they all reach a satisfactory solution to my problem within less than **20** generations.

The problem that I face is that it takes very long time to initialize the task which is almost constant regardless of algorithm. By initialization, I refer to:

- Problem initialization via `pg.problem(my_problem_Class)` takes approx **90s**, regardless of algorithm
- Population initialization via `pg.population(my_problem_Object, size=10)` takes approx **110s**, regardless of algorithm

Why is that?

Many thanks,
/Panagiotis

**Comment by darioizzo** [comment]
Well, you need to give us more detail to understand what is gong on. Do you have maybe a minimal example?

* Problem initialization should take as much time as UDP initialization. So ```pg.problem(my_problem_Class())``` and ```my_problem_Class()``` should take the same time. Is this the case?
* Population initialization takes the time to construct a ```my_problem_Class()``` object and ```size``` calls to the fitness function to init the individuals.

**Comment by pcko1** [comment]
Thanks a lot for the answer. 

Below I have a minimal example using a very simple [Keras ](https://keras.io/) feedforward neural network. The network I use in my case is considerably more complex, but the one here demonstrates the issue: it takes around 10s to instantiate the `pg.problem(MyProblem())` on my machine whereas `MyProblem()` is almost instant .


```
import pygmo as pg
import numpy as np
from datetime import datetime

# Neural network dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense

class MyProblem():
    def __init__(self, model, dim=128, lb=-3, ub=3):
        # Neural network
        self.model = model
        # Number of variables
        self.dim = dim
        # Upper/lower bounds for the input variables
        self.lb = lb
        self.ub = ub
    
    # Minimal fitness function
    def fitness(self, x):
        # Make sure of the shape
        x = np.reshape(x, (1,128))
        y = self.model.predict(x)
        # Return um of elements of y
        return np.sum(y) 
    
    def get_bounds(self):
        return ([self.lb] * self.dim, [self.ub] * self.dim)
    

# Simple untrained Keras neural network
model = Sequential()
model.add(Dense(128, input_dim=128, activation="relu"))
model.add(Dense(512))
model.add(Dense(512))
model.add(Dense(512))
model.add(Dense(1))
model.compile(optimizer="sgd", loss="mse")

# Custom problem instantiation
tstart  = datetime.now()
my_prob = MyProblem(model=model, dim=128, lb=-10, ub=10)
print("Finished in %i seconds." % (datetime.now()-tstart).seconds)

# pg.problem instantiation
tstart  = datetime.now()
pg_prob = pg.problem(my_prob) 
print("Finished in %i seconds." % (datetime.now()-tstart).seconds)
```

**Comment by bluescarni** [comment]
I cannot reproduce the issue using the code above. I copy/pasted the code verbatim in a Python file, ran it, and this is the output:

```console
Using TensorFlow backend.
Finished in 0 seconds.
2019-03-05 14:26:27.228683: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-05 14:26:27.228703: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-05 14:26:27.228708: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-03-05 14:26:27.228713: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-05 14:26:27.228718: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Finished in 0 seconds.
```

Warnings apart, the creation of the problems seems to be instantaneous.

Something to keep in mind is that the creation of a pygmo problem causes the deep-copy of the ``MyProblem`` object, which in turns contains a ``model`` object. My original conjecture was that the copy operation of ``model`` was taking long.

I ran the test from a conda installation using pygmo 2.10.

**Comment by darioizzo** [comment]
Indeed that is also my thought, the model when copied will be compiled again. So the operation ```model.compile(optimizer="sgd", loss="mse")``` is called upon pg.problem construction. And that takes usually long.

@pcko1 Can you time how slow are the lines:
```
model = Sequential()
model.add(Dense(128, input_dim=128, activation="relu"))
model.add(Dense(512))
model.add(Dense(512))
model.add(Dense(512))
model.add(Dense(1))
model.compile(optimizer="sgd", loss="mse")
```

?

**Comment by pcko1** [comment]
@bluescarni Thanks a lot for the heads-up about **deepcopying** of the `model`, this is probably the issue in my case since my actual `model` object contains 3 LSTM neural networks in series, making it probably a demanding model to deepcopy.

@darioizzo In this minimal example, those lines take **98737us** or **~0.1s** on my computer.

**Comment by darioizzo** [comment]
@pcko1 Something does not add up .... I think there is an issue with keras model serialization. Should you not pass the hd5 file and not the model? See also: https://github.com/keras-team/keras/issues/1765

**Comment by bluescarni** [comment]
If I interpret well the discussion in that issue, you might need to call a special ``clone()``-type function to deep-copy a model? If that's the case, then you can customise the copy/deepcopy protocol of your ``MyProblem`` problem to invoke the ``clone()`` method of the model.

See, e.g., here on how to customise (deep)copy:

https://stackoverflow.com/questions/1500718/what-is-the-right-way-to-override-the-copy-deepcopy-operations-on-an-object-in-p

**Comment by bluescarni** [comment]
I will go ahead and close the report, as it looks like this might be a serialization performance issue in keras. Please @pcko1 re-open if needed.
