### ISSUE TITLE
Install issues 

### ISSUE THREAD

**Issue by pshober** [esa/pagmo2#254]
Currently I am using Debian 9 Stretch. PyGMO seems to be installed but some of the dependencies do not seem to be downloaded. For example, when I try some of the examples it won't be able to find _'problem.messenger_full()'_. _'problem'_ is found but there is no attribute called _'messenger'_. 

When I try to use the cmake utility  I get the following error after configuring: 

> CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1534 (message):
>    No header defined for python3; skipping header check
>  Call Stack (most recent call first):
>    CMakeLists.txt:99 (FIND_PACKAGE)
> 
>  CMake Error at CMakeLists.txt:116 (MESSAGE):
>    I cannot find the keplerian_toolbox library or headers, please install it
>    and make sure it can be found

Any help would be greatly appreciated ! Cheers!

**Comment by darioizzo** [comment]
I think this a pagmo 1.x issue, not pagmo2. Note that on pagmo2 the GTOP problems are not supported (i.e. no messenger, cassini etc...) and that pagmo2 does not depend on the keplerian toolbox.

The new keplerian toolbox will support in the future these features, but not at the moment.

So if you need those capabilities, you will need to install old versions. 

I will close this as its not a pagmo2 issue.
