### ISSUE TITLE
Benchmarking algorithms/ Accessing information inside archipelago

### ISSUE THREAD

**Issue by lucialenasophie** [esa/pagmo2#260]
Hi,

I would like to compare several MO-algorithms by running them multiple times and then comparing metrics such as hypervolum, p_distance, etc. for performance assesment and validation.

My first attempt was this; for example using dtlz1, moead and p_distance:

```
import pygmo as pg

dim = 5 #dimension of the test problem
fdim = 2 #number of objective functions
dtlz1 = pg.dtlz(prob_id =1, dim = dim, fdim = fdim)
pop = pg.population(prob = dtlz1, size = 105)
algo = pg.algorithm(pg.moead(gen = 100))

for i in range(10):
  print(dtlz1.p_distance(pop))
  pop = algo.evolve(pop)
  print(dtlz1.p_distance(pop))

```

When I checked the result, I realized that the initial p_value of one run equals the final p_value of the run before, so these do not seem to be independent calculations.
So my first question is: What exactly is happening in this loop and why are the different runs connected?

My next attempt was to use an archipelago: 

`archi = pg.archipelago(n=32, algo=algo, prob=dtlz1, pop_size=70)`

However, I can not figure out how to acces the different island in order to perform calculations on them as in the first example. My second question would be: How can I do that?

And at last, general questions: Is this a reasonable way to compare algorithms or is there are better approach?

Thank you.

**Comment by darioizzo** [comment]
The population contains you initial chromosomes .. when evolve is called the chromosomes are only evolved. When you create a non empty pop the chromosomes are inited at random in the bounds.

If you want independent runs you need to construct a new population inside the loop, or manually set the initial values of the chromosomes.

**Comment by lucialenasophie** [comment]
Hi,

moving the population inside the loop worked fine, thank you!

**Comment by bluescarni** [comment]
Closing the issue, please feel free to re-open if needed.
