### ISSUE TITLE
Installation on windows in Python 3

### ISSUE THREAD

**Issue by Farzadtb** [esa/pagmo2#263]
Hi all

I followed [this link]([url](https://esa.github.io/pagmo2/install.html)) to install pygmo on Python 3 on windows, so it should have been simply pip install pygmo like [here ](https://pypi.org/project/pygmo/)

but when I check and ran the [example here](http://esa.github.io/pygmo/)

Python did not know the cassini_1() problem, as it was not installed..

the installation[ guides here ](http://esa.github.io/pygmo/install.html) are different from the previous one, and more elaborated and not clear how to do in Python , I don't even know how to do that

**Comment by Farzadtb** [comment]
Why is this package sooooo compllicated ? I am now having to follow installing Mingw with its own problems to install boos and git and cmake http://mingw.org/wiki/Getting_Started

**Comment by bluescarni** [comment]
You are mixing up the documentation from the previous version of pagmo/pygmo (1.x) with the current one (2.x). pagmo/pygmo 1.x and 2.x are different and separate libraries, although with many similarities.

The ``cassini_1()`` problem is not part of pagmo/pygmo 2.x, as for version 2.x the decision was made to split out domain-specific optimisation problems into distinct affiliated packages. Perhaps @darioizzo can be more precise about this, as he is the main author of the astrodynamical problems for pagmo/pygmo.

Our suggestion, generally speaking, is to install pagmo/pygmo under Windows using the conda package manager, as the ``pip`` packages are currently in maintenance-only mode and their future is uncertain.

I will go ahead and close this report for the time being, if you have further issues with pagmo/pygmo installation please open a new report.
