### ISSUE TITLE
When using an archipelago, which arguments correspond to processor count?

### ISSUE THREAD

**Issue by doctorpangloss** [esa/pagmo2#271]
I'm sure you have a good reason for the jargon you guys use but it's unclear what actually results in parallel threads?

Given:

```
import pygmo as pg
import multiprocessing
algo = ...
problem = ...

pg.archipelago(n=A, algo = algo, prob = problem, pop_size=B)
archi.evolve(C)
archi.wait()
```

**What is the relationship between A, B, C and `multiprocessing.cpu_count()`?**

I'm really struggling because you use these words in your quickstart:

```
# 4 - Run the evolution in parallel on the 16 separate islands 10 times.
archi.evolve(10)
```

Like I know you mean from an algorithmic perspective, a champion is found "in parallel." But obviously, for performance reasons, I'm interested in making this computation parallel. I think you should really consider using different words here!

**Comment by darioizzo** [comment]
Not sure I understand your issue here. The number of processors (threads, processes or whatever is used by the underlying island type) will, roughly, be the number of islands, that is `n`.

I agree that `n` is not a good name for the respective kwarg, we may consider using `n_isl` or `arch_size`
