### ISSUE TITLE
About ideas list

### ISSUE THREAD

**Issue by xiaoerlaigeid** [esa/pagmo2#274]
Dear mentor，
 
I am a senior student majoring in Computer Science. I am interested in working on this project. Could you please offer me some detail information about this project. And how could I start the project ? I plan to learn something about this.

**Comment by darioizzo** [comment]
This is not an issue with pagmo code. Closing it. 

In case you need to discuss projects and possible contributions to the code base, please join our community in gitter: https://gitter.im/pagmo2/Lobby
