### ISSUE TITLE
Tests fail to build on muiltiple CPUs due to failed build parallelism

### ISSUE THREAD

**Issue by yurivict** [esa/pagmo2#275]
See the log: https://people.freebsd.org/~yuri/pagmo2-test-1.log

**Comment by bluescarni** [comment]
Not sure exactly what that means. Could you help me interpret the output?

I normally use the ``make`` generator for CMake, rather than the ``ninja`` generator. But I just tried a build with the ``ninja`` generator and it worked fine (debug build with all optional deps + test building).

**Comment by yurivict** [comment]
It uses some object files before they are built. Dependencies aren't correct somewhere, not sure why and how.

**Comment by yurivict** [comment]
This doesn't happen every time. This happened for me during the second run, when the machine was overloaded.

**Comment by bluescarni** [comment]
Could it be that some process is killed during compilation because of excessive memory usage? How many processors are being used in parallel in the build?

The current pagmo is very memory hungry during the compilation of the tests, we are working on improving the situation.

**Comment by yurivict** [comment]
This machine has 8 virtual CPUs and 24 GB of memory. Processes don't get killed due to memory use on FreeBSD AFAIK.

**Comment by bluescarni** [comment]
Would it be possible for you to try with the makefile generator?

At the moment I can't think of anything special in our build system that would break parallel compilation, which we are using without issues since a long time on multiple operating systems.

**Comment by bluescarni** [comment]
@yurivict The new pagmo release, 2.11, is out. Could you please re-try a FreeBSD build?

**Comment by bluescarni** [comment]
Closing for the time being as this has not been triaged on the latest pagmo version. @yurivict feel free to re-open if you experience the same issue on the latest pagmo.

**Comment by bluescarni** [comment]
@yurivict any chance you could try updating the FreeBSD port of pagmo/pygmo with the latest versions?

**Comment by yurivict** [comment]
The OP doesn't occur any more.

I'll update the FreeBSD port to the latest revision.

Thanks!

**Comment by bluescarni** [comment]
> The OP doesn't occur any more.
> 
> I'll update the FreeBSD port to the latest revision.
> 
> Thanks!

@yurivict Cheers!

Just FYI, a while ago we split pagmo & pygmo in 2 separate projects, with pagmo now being a dependency for pygmo. pygmo is hosted here:

https://github.com/esa/pygmo2

I don't recall if the FreeBSD port was building both pagmo and pygmo at the same time, but in such a case you would need two separate ports now.

**Comment by yurivict** [comment]
I've added the FreeBSD port for pygmo2.

Thanks for letting me know.

**Comment by bluescarni** [comment]
> I've added the FreeBSD port for pygmo2.
> 
> Thanks for letting me know.

Awesome, thanks a lot!
