### ISSUE TITLE
Optional Dependencies Support

### ISSUE THREAD

**Issue by acxz** [esa/pagmo2#276]
Is there any reason as to why during the build process, users need to specify optional dependencies to be compiled against? I think by default pagmo should be compiled against the optional dependencies if they exist on the users system. There should be no need to enable flags for these dependencies when building against them, if the user already has the dependencies installed.

**Comment by bluescarni** [comment]
We have a long standing policy of preferring explicitly declaring the optional components to use.

We have been bitten repeatedly by automatic dependency detection in the past and it was just too much trouble. Explicit is better than implicit :)

Closing the report as this is an explicit design decision.

**Comment by acxz** [comment]
I understand, however, I am saddened. This makes packaging slightly more difficult
