### ISSUE TITLE
Create uninstall target for CMake

### ISSUE THREAD

**Issue by acxz** [esa/pagmo2#280]
Right now there is no uninstall target for CMake, which makes it hard to uninstall pagmo after installing it from source. I believe having the ability to `sudo make uninstall` is very helpful and much wanted.

**Comment by acxz** [comment]
Went ahead and submitted #282 for this issue. One problem is that the solution submitted does not remove empty folders created during installation. I did find a solution that does that, but I not sure how the licensing for that module works. I would be happy if somebody could take a look at it. Here is the uninstall module: [Link](https://github.com/cmake-basis/BASIS/blob/master/src/cmake/modules/cmake_uninstall.cmake.in) and the license/copying information for the project: [Link](https://github.com/cmake-basis/BASIS/blob/master/COPYING.txt).

**Comment by bluescarni** [comment]
Closed by #282, thanks!
