### ISSUE TITLE
Installing with IPOPT

### ISSUE THREAD

**Issue by mpowelson** [esa/pagmo2#291]
I am running into some issues when trying to install Pagmo with IPOPT.

When pulling 2.10 I can compile and install pagmo, but I get the error `IpIpoptApplication.hpp: No such file or directory
compilation terminated.` any time I try to include ipopt.hpp.

Thinking there might have been a bug fix I pulled master, but on master I cannot get Pagmo to compile. I get some errors like this
 ```
In file included from /home/mpowelson/workspaces/temp/ext/pagmo2/include/pagmo/algorithms/ipopt.hpp:46:0,
                 from /home/mpowelson/workspaces/temp/ext/pagmo2/src/algorithms/ipopt.cpp:67:
/home/mpowelson/workspaces/temp/ext/pagmo2/include/pagmo/algorithms/not_population_based.hpp:115:57: error: invalid initialization of non-const reference of type ‘long unsigned int&’ from an rvalue of type ‘long unsigned int’
             ar << boost::any_cast<population::size_type>(m_replace);
```
I've tried installing the IPOPT debian as well as building it from source and neither of those things seem to make a difference.

**Comment by bluescarni** [comment]
In the first issue, it sounds like you forgot to add ipopt's include dirs when compiling your code.

The second issue is probably a problem with older boost versions. Are you using Boost < 1.60? See here for a description of the likely problem:

https://github.com/venediktov/vanilla-rtb/issues/53

**Comment by bluescarni** [comment]
@mpowelson to give a bit of context, we recently switched serialization library to Boost's implementation. In pagmo 2.10, we were still using our own internal copy of the cereal library, which is now gone in the master branch. That's why you are experiencing a compilation error only in master and not in 2.10.

We are planning to bump up the minimum required Boost version to 1.60 in light of this bugreport.

**Comment by mpowelson** [comment]
Yes, I am using an older Boost version on Ubuntu 16.04.  For now I can just use the release version and worry about upgrading Boost later. 

Is there something I need to do to include IPOPT? When running cmake as below it seems to find it, and that header file is in the directory it found
```
cmake .. -DPAGMO_WITH_EIGEN3=ON -DPAGMO_WITH_IPOPT=ON -DPAGMO_WITH_NLOPT=ON
-- System name: Linux
-- The fork_island UDI will be available.
-- The C++ compiler ID is: GNU
-- YACMA autodetected C++ flags: -fdiagnostics-color=auto;-ftemplate-depth=1024;-fvisibility-inlines-hidden;-fvisibility=hidden
-- YACMA autodetected C++ debug flags: -Wall;-Wextra;-Wnon-virtual-dtor;-Wnoexcept;-Wlogical-op;-Wconversion;-Wdeprecated;-Wold-style-cast;-pedantic-errors;-Wdisabled-optimization;-ftemplate-backtrace-limit=0;-fstack-protector-all;-Wsuggest-attribute=pure;-Wsuggest-attribute=const;-Wsuggest-attribute=noreturn;-Wsuggest-attribute=format;-Wodr;-Wsuggest-final-types;-Wsuggest-final-methods;-Wsuggest-override;-Wno-maybe-uninitialized
-- Thread library: -pthread
-- POSIX threads detected.
-- POSIX threads affinity extensions detected.
-- The 'thread_local' keyword is supported.
-- Eigen include directory: /usr/include/eigen3
-- Eigen version detected: 3.2.92
-- NLopt include directory: /usr/local/include
-- NLopt library: /usr/local/lib/libnlopt.so
-- Ipopt include directory: /usr/local/include/coin
-- Ipopt library: /usr/local/lib/libipopt.so
-- Required Boost libraries: 
-- Boost version: 1.58.0
-- Detected Boost version: 105800
-- Boost include dirs: /usr/include
-- The 'Boost::boost' target is missing, creating it.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mpowelson/workspaces/temp/ext/pagmo2/build

```

**Comment by darioizzo** [comment]
can you post the full error you get?

**Comment by darioizzo** [comment]
Also in #292 I have upped the boost requirment to 1.60, so that when the PR is accepted we can close this.

**Comment by mpowelson** [comment]
```
In file included from /home/mpowelson/workspaces/temp/src/trajopt/trajopt_examples/src/pagmo_example.cpp:9:0:
/usr/local/include/pagmo/algorithms/ipopt.hpp:36:34: fatal error: IpIpoptApplication.hpp: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/pagmo_example.dir/src/pagmo_example.cpp.o] Error 1
make[1]: *** [CMakeFiles/pagmo_example.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by darioizzo** [comment]
ok so you are trying to compile your own cpp file using a version of pagmo ypou have installed in your system.

Can you post here the compile line you use to compile ```pagmo_example.cpp```

**Comment by mpowelson** [comment]
Yes that is correct. Sorry I didn't specify that. I'm not using cmake directly to compile pagmo_example.cpp. I'm using catkin_tools. I don't fully understand what would you like me to provide.

Here's bits of the CMakeList that deals with the example.

```
find_package(pagmo REQUIRED)
catkin_package()

include_directories(
  ${catkin_INCLUDE_DIRS}
  SYSTEM ${PCL_INCLUDE_DIRS} ${pagmo_INCLUDE_DIRS}
)

add_executable(pagmo_example src/pagmo_example.cpp)
target_link_libraries(pagmo_example ${catkin_LIBRARIES})
target_compile_options(pagmo_example PRIVATE -Wsuggest-override -Wconversion -Wsign-conversion)
```

**Comment by mpowelson** [comment]
Also, for what it's worth, it does work fine when I remove the IPOPT header.

**Comment by darioizzo** [comment]
Ok so you are using CMake as a build system to build your own cpp file which is using pagmo as a dependency. 

Your CMakeList is incorrect as it does not link to the pagmo target and hence it does not add the correct header paths. I will shortly post to you the correct way of doing this ....

**Comment by bluescarni** [comment]
@mpowelson ``find_package(pagmo)`` is the correct way of looking for a pagmo installation from CMake. The last step that you are missing is to link to the ``Pagmo::pagmo`` imported target. That is, rather than using ``include_directories()``, just write

```cmake
target_link_libraries(pagmo_example Pagmo::pagmo)
```

This should take care of everything: add pagmo's (and pagmo's dependencies') include paths, and link pagmo (and pagmo's dependencies) to the ``pagmo_example`` executable.

Let us know how it goes.

**Comment by mpowelson** [comment]
It looks like that did fix it. Thanks for your help.
