### ISSUE TITLE
nsga2 example broken

### ISSUE THREAD

**Issue by MLopez-Ibanez** [esa/pagmo2#313]
The example here:

https://esa.github.io/pagmo2/docs/cpp/tutorials/evolving_a_population.html

does not work anymore.

It needs:

#include <pagmo/io.hpp>

(To avoid this in the future, examples should be built and tested in continuous integration)

**Comment by bluescarni** [comment]
CC #285

**Comment by bluescarni** [comment]
Being addressed in #340.

**Comment by bluescarni** [comment]
Fixed.
