### ISSUE TITLE
Extracting attribute from a unconstrained problem 

### ISSUE THREAD

**Issue by lstubbig** [esa/pagmo2#316]
Hello,
I am using an unconstrained meta-problem in Pygmo and am trying to extract an attribute of my problem class after the optimization is finished. I am using this attribute to store intermediate values of the optimization process in a dictionary. With the original problem this works fine like this:
>history = myPopulation.problem.extract(object).history

For the unconstrained meta-problem this fails and I am somehow not able to access the inner problem that should be available inside the meta-problem. For example, this works, but shows the state before evolving the population:
>history = myProblem.inner_problem.extract(object).history

Is there a way to do something like this?
>history = myPopulation.myProblem.inner_problem.extract(object).history

Thanks!

**Comment by bluescarni** [comment]
@lstubbig could you provide a snippet of code which reproduces the problem?

It's a bit difficult to interpret the problem as it is not clear from your code which types are involved. If you have a pygmo ``problem`` containing an ``unconstrain`` meta-problem and you want to access the ``history`` property of the original UDP, you will have first to extract the ``unconstrain`` meta-problem and then extract again the original UDP from its ``inner_problem``. E.g., something along these lines:

```python
class my_udp:
   ...

unc = pygmo.unconstrain(my_udp(), ...)
prob = pygmo.problem(unc)

prob.extract(pygmo.unconstrain).inner_problem.extract(my_udp).history
```

(I don't have a pygmo installation on this computer, so beware that the code above is untested)

You also seem to imply that the ``history`` attribute is the original one after an evolution. That might indicate a problem in pygmo, but I would like to understand what's going on before digging into that.

**Comment by lstubbig** [comment]
Hello, 
thank you for the fast reply. That helped a lot. I will try to give some more context about what I did. 
I have a UDP like this:
 ```python
class myProblem:
    def __init__(self):
        self.history = {'x':[]}
    def fitness(self, x):
        fitness = ...
        ineq = ....
        self.history['x'].append(x)
        return [fitness, ineq]
```
Then I run the optimization like this
```python
prob = pg.problem(pg.unconstrain(prob=myProblem(), method='ignore_c'))
algo = pg.algorithm(pg.sga())
pop = pg.population(prob, 30)
pop = algo.evolve(pop)
```
When I then extract the `history` attribute from the problem like you suggested above `history` contains the initialized dictionary but not the appended values, which I think is expected behaviour. I have to get the 'processed' problem from the evolved population to retrieve those values:
```python
history = pop.problem.extract(pg.unconstrain).inner_problem.extract(object).history
```
This works! My problem was two-fold: I used `prob = pg.unconstrain(prob=myProblem(), method='ignore_c')` without the outer `pg.problem` which didn't result in any errors and ran fine. Is that wanted? 
And I did not specify the type in `extract(type)`. For the original problem it is possible to just put `history = pop.problem.extract(object).history` but for the meta-problem it seems to be necessary.
Thanks again!

**Comment by bluescarni** [comment]
When you construct a population from a problem, the problem object gets deep copied inside the population, and the population's copy of the problem is used in the subsequent evolutions. Thus, the ``history`` attribute of the original ``prob`` object will not be altered by the evolutions, as you correctly inferred.

Regarding ``extract()``, it used to require to pass in the correct type for the extraction to succeed. Recently, I modified it so that if your problem is implemented in Python, you don't need to pass the correct type and using just ``object`` instead will work. Note, however, that ``unconstrain`` is a C++ implemented UDP, so if you want to extract an ``unconstrain`` from a ``problem`` you need to pass in the correct type.
