### ISSUE TITLE
Uncertainty estimation in the fitted parameter output

### ISSUE THREAD

**Issue by denisbertini** [esa/pagmo2#336]
Hi
Just 2 questions. 

1 ) Is there some way  to estimate uncertainty in the fitted parameters output
   with PAGMO ?

2) With how many cores ( MPI version of PAGMO ) can one works with the parallel
 version of PAGMO ( is there already some benchmark?) .  

Thanks in advance

**Comment by bluescarni** [comment]
Regarding 1), I'll let @darioizzo reply when he's back from holidays.

Regarding 2), please note that pagmo2 does not have MPI support yet, although that is planned eventually. There should be no limit to the number of cores that pagmo can employ (and there was no such limit in pagmo1 either). The only possible bottleneck is that there is a single node in the cluster which acts as a coordinator. This should not be a practical issue as long as there's enough work to be distributed across the other nodes of the cluster.

**Comment by denisbertini** [comment]
Humm and what if the unique "coordinator" machine dies ... Actually, even worse,  if any node where MPI is running has a problem then the complete MPI job will then also crash, standard
behaviour of MPI  ( MPI Fatal )
How to you cope with the non-resilience of MPI library?

**Comment by bluescarni** [comment]
Are you talking about a cluster node hard crashing for external causes (e.g., power outage), or "softer" termination conditions (e.g., time limit for a job reached)?

For the first case, I don't think there's much we can/should do. I've been working fairly regularly with large HPC clusters in the last couple of years and I can remember perhaps one instance of unscheduled downtime of computing nodes. Do you have a specific use case in mind of computing nodes going down relatively frequently?

For the second case, probably we can do something in terms of how gracefully pagmo reacts to a SIGINT/SIGTERM signal. If I recall correctly, in pagmo1 we had some specific messages that instructed the worker nodes to shut down gracefully. Probably we'll have something like that in pagmo2 as well.

FYI, I was a bit incorrect when I talked about "MPI support". The tentative plan for pagmo2 is not to go for bare MPI, but rather to use HPX:

https://github.com/STEllAR-GROUP/hpx

HPX can run on top of MPI (so this ensures that you will be able to run pagmo2 on standard cluster architectures), but it provides a much nicer C++-ish way of implementing cluster-level parallelism.

**Comment by denisbertini** [comment]
Hi
I think that unscheduled downtime of computing node  + any kind of networks disruption in a large HPC cluster is always an issue. 
I do not know about HPX but it seems not easy to use and kind of beta code ?
What makes you sure that HPX is a "better" MPI ?

**Comment by bluescarni** [comment]
There's a couple of reasons about the HPX choice.

First, it's a modern C++ codebase, closely tracking the latest developments of the C++ standard in terms of parallelism and concurrency. But even if it was "just" a C++ wrapper over MPI (which it isn't), I would still prefer it over plain MPI. There's no way I am going back to writing C-style code if I can avoid it at all :)

Secondly, the type of coarse-grained parallelism implemented in pagmo (with the islands, the migration model, etc.) is not a very good match for MPI-style parallelism. The computational workloads can be very uneven and it's essentially impossible to establish a good a-priori partitioning scheme for parallel computations which works reasonably well in all cases. In pagmo1 we essentially implemented an ad-hoc tasking/load balancing system on top of MPI. It did work, with various limitations (e.g., nested parallelism was not working, which barred certain use cases which were trivial on a single multi-threaded machine), but I'd rather not have to re-implement such a system in pagmo2 on our own. By comparison, HPX has various builtin facilities for task-oriented parallelism, load balancing, nested parallelism, and so on.

I understand that HPX is less well-established that MPI, but, given the potential advantages, it's a risk I am willing to take.

With that said, that's my own point of view (i.e., the point of view of the person who will have to do the job). If anyone wants to implement an alternative, pure-MPI based parallelisation scheme for pagmo, they are very much welcome to do so - we would certainly not refuse any contribution in this sense. Pagmo itself won't have a hard-coded dependency on HPX or anything of the sort, the HPX parallelisation will be implemented as an extension and not in the "core" of the library.

PRs welcome, as usual :)

**Comment by denisbertini** [comment]
Is there in Pagmo2 some way already implemented to estimate uncertainties or parameter sensitivity ?

**Comment by darioizzo** [comment]
Closing this. Discussion can continue on gitter if needed. Please clarify there what parameters and in what context.
