### ISSUE TITLE
Expose in pygmo various utility functions

### ISSUE THREAD

**Issue by bluescarni** [esa/pagmo2#34]
- [x] It would be nice if all the utility functions available on the C++ were available in Python as well. E.g., all the constrained optimization sorting utils are not exposed in Pygmo.
- [x] Once this is done, the docstrings of ``population`` in pygmo should be modified to refer to the exposed sorting utils, rather than to the C++ ones.
- [x] We should probably export also the bits from ``rng.hpp`` to offer seed control to the Python users.

**Comment by darioizzo** [comment]
These have all been addressed in #76. When merged the issue can be closed.
