### ISSUE TITLE
Move the expose_not_population_based into the public pygmo interface

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo2#344]
At the moment ``expose_not_population_based`` is here https://github.com/esa/pagmo2/blob/master/pygmo/expose_algorithms.hpp#L65, this prevents AP (affiliated packages) to use it. 

Would it be possible to move it in the public pygmo interface, for example in https://github.com/esa/pagmo2/blob/master/pygmo/algorithm_exposition_suite.hpp#L56?

**Comment by darioizzo** [comment]
This is now needed also for the dcgp affiliated packages ....

**Comment by darioizzo** [comment]
I log here another possible improvement for APs.

If dill is not installed upon ```import my_ap``` an exception is thrown "SystemError: initialization of core raised unreported exception". A better message could be displayed, similar to the one pygmo gives in the similar occasion.

**Comment by bluescarni** [comment]
I am trying to understand how the dill error might happen... as far as I remember, we never import dill from the C++ exposition code. Do you have some code which reproduces the problem?

I have not been able to fix unhelpful error messages during the module initialization phase. To the best of my recollection, this was a limitation in Boost.Python. We should probably postpone the fix when we move to pybind11.

**Comment by bluescarni** [comment]
On second thought, perhaps the missing package was ``cloudpickle`` rather than ``dill``? cloudpickle is our default serialization backend, unless you manually change that ``dill`` should never enter the picture.

**Comment by darioizzo** [comment]
likely ... I just said dill randomly, probably cloudpickle was the issue..... should I check?

**Comment by bluescarni** [comment]
``expose_not_population_based()``  has been moved to the APs headers in #361.

**Comment by bluescarni** [comment]
@darioizzo gonna close this for now, please re-open if there are further issues (and open a new report if you still encounter the ``dill`` issue).

**Comment by anhvt2** [comment]
I also ran into the same issue.

```python3
>>> import pygmo as pg
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
====ERROR====
The cloudpickle module could not be imported. Please make sure that cloudpickle has been correctly installed.
====ERROR====
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pygmo/__init__.py", line 33, in <module>
    from .core import _cleanup as _cpp_cleanup
SystemError: initialization of core raised unreported exception
```

**Comment by anhvt2** [comment]
solved. upgrading ```numpy``` solves the problem
