### ISSUE TITLE
MOEAD algorithm: ideal points in log do not match ideal points of final population

### ISSUE THREAD

**Issue by vathomass** [esa/pagmo2#357]
Hi,
I am trying to solve a multi-objective optimization problem with the algorithm MOEAD. The ideal points reported in the log of MOEAD do not match the ideal point in my final population, as I would expect. A minimal example to reproduce the issue:
```python
prob = pygmo.problem(pygmo.dtlz(prob_id = 1, dim = 5, fdim = 2))
pop_init = pygmo.population(prob=prob, size=50, seed=111111)
algo = pygmo.algorithm(pygmo.moead(gen=30, neighbours=20, decomposition='bi', seed=222222))
moead = algo.extract(pygmo.moead)
algo.set_verbosity(1)
pop = algo.evolve(pop_init)
```

The final log entry when running the above script is: `30, 1450, 1195.4509096361207, 0.00506679, 0.0213844` (the last 2 values should by the ideal points of the last generation) and the ideal points returned by
```python
pygmo.ideal(pop.get_f())
```
are `0.01223206, 0.61659663`.

Best
Thomas

**Comment by darioizzo** [comment]
First I am logging this here at it seems there are other small issues with the moad code:
* [ ] https://github.com/esa/pagmo2/blob/master/src/algorithms/moead.cpp#L248
this to me is a repetition as the for loop above seems to be doing the same thing. I would remove the loop and leave the transform.

As for the ticket raised, looking at the moead code I am seeing a possible explanation.  The ideal point is updated immediately after mutation (https://github.com/esa/pagmo2/blob/master/src/algorithms/moead.cpp#L248) regardless wheather the individual is inserted into the population or not (line https://github.com/esa/pagmo2/blob/master/src/algorithms/moead.cpp#L255)

**Comment by darioizzo** [comment]
Note that the reported difference between the last logged ideal and the idal of the final population may also appear in other algorithms (nsga2, for example) as the logs do not log the very last iterations ... something that should be fixed across udas.

All udas should log one entry line, the requested lines during evolution, and one exit line. This is not the case at the moment.

**Comment by ow97** [comment]
Possibly related issue:

> My UDP's optimal solution if fairly likely to on the boundary of the feasible region defined by the box bounds. This is expected; outside my box bounds the problem ceases to be defined/make any sense.
> 
> Unfortunately I'm having trouble with MOEAD being somehow "reluctant" to find solutions where the decision vector lies at the boundary of the box bounds. This behaviour is not observed with e.g. NSPSO which correctly converges to solutions at the boundary.
> 
> Is this behaviour of MOEAD expected?
> 
> Am I best to work around the issue by expanding my box bounds and then imposing some inequality constraint that actually defines the feasible region of my problem or would you recommend some other approach?
> MOAD has currently a small issue when it comes to getting the extreme point of the Pareto front. Is this the issue you are encountering? Or you think it's a different issue?
> From your description it is possible that these are the same issue. The observable effect for me is that as any part of the Pareto front approaches the box bounds the rate of approach decreases exponentially, such that the bound is never reached.

That is to say that the observable effect for me is that as any part of the Pareto front approaches the box bounds the rate of approach decreases exponentially, such that the bound is never reached.

**Comment by darioizzo** [comment]
One more note on MOEAD performances ... when the uda is seeded from some external solution that we know to be good (in the pareto front)
