### ISSUE TITLE
Some questions on Pygmo

### ISSUE THREAD

**Issue by gfadini** [esa/pagmo2#360]
Hello, 
I'm using Pygmo for a bi-level optimization of some parameters in a co-design framework. Basically I use pygmo in the outer loop, for setting the parameter of the model and optimize a UDP with CMEAS while in the inner loop I use another library with python bindings for optimal control that deals with the dynamics of the system. I would like to ask you:

- since I'm interested topology and archipelagos for massively parallel optimization strategies is there a tutorial for that for the Python version?
- is there support for integer programming optimization (since some optimizations set may be not continuous and using integer conversion may not be super efficient)
- are there any DoE functions already implemented to do some kind of sensitivity analysis or is that all to do in the post-processing?
- is there a quick way to continue the optimization from a previous "exploration" of the problem?

**Comment by darioizzo** [comment]
Hi, 

I will close this as its not an issue. PLease discuss questions related to the use of pagmo in the gitter channel (https://gitter.im/pagmo2/Lobby).

Some short (probably incomplete) answers:

* No, docs on migration are to come.
* Yes, see problem docs. The get_nix method of the UDP define the integer part.
* I did not get your question.
* Yes. Just call evolve again on the population (or archi).
