### ISSUE TITLE
Always to few islands in fully_connected topology

### ISSUE THREAD

**Issue by vesdakon** [esa/pagmo2#364]
I upgraded to the latest pagmo 2.11.4 (on Ubuntu) and is trying to get the fully_connected topology to work. What is the relation between the vertices and islands parameter in pagmo2. Whatever combination I try I get this or similar:
terminate called after throwing an instance of 'std::out_of_range' 
what(): function get_migrants
where: /home/anders/pagmo-build/pagmo2-master/src/archipelago.cpp 644
what: cannot access the migrants of the island at index 6: the migrants database has a size of only 4.
I have tried islands=4, vertices=6 guessing that you should give the max no of vertices with given no of islands. I have  tried islands=20 and vertices=2 and other combinations, but I always get that I do not have enough islands. I realize that I do not  understand the relation between the parameters. 
This is an example of part of my code:
    int gen = 2000;
    int popul = 35;
    int evolve = 30;
    problem prob{problem_owp{}};
    int cstrs_iters = 30;
    algorithm algo{cstrs_self_adaptive(cstrs_iters, de1220(gen))};
    long unsigned int islands = 10;
    double edge_weight = 0.5;
    std::size_t number_of_vertices = 2;  
    archipelago archi{fully_connected{number_of_vertices,edge_weight}, islands, algo, prob, popul};
    archi.evolve(evolve);
    archi.wait_check();
Maybe fully_connected is not fully implemented yet?
Thanks!
Anders Vesterberg

**Comment by darioizzo** [comment]
For questions and help on the code usage, please use our gitter channel: https://gitter.im/pagmo2/Lobby. Also, please use syntax highlighting for code snippets (check the markdown syntax to use in gitter) as to allow us to help.

**Comment by bluescarni** [comment]
@vesdakon When you create an archipelago with ``n`` islands, the archipelago constructor will take care of adding the islands to the topology. Thus, it should be enough to pass to the archipelago constructor a fully connected topology inited with 0 islands.

As @darioizzo said, please use the gitter channel for this type of questions.
