### ISSUE TITLE
population.push_back() - champion is not updated in population

### ISSUE THREAD

**Issue by waldemar-martens** [esa/pagmo2#366]
When using the push_back() method of the population class, the champion in the population is not updated if new newly added solution is better than the previous champion and the previous population size is larger than 3. It also seems like the algorithm doesn't use the newly added individual when being evolved. A minimal example is attached (Pygmo 2.11.4):

```
#import pygmo as pg
import math


class my_constrained_udp:
    # UDP from Python tutorial
    def fitness(self, x):
        obj = 0
        for i in range(3):
            obj += (x[2*i-2]-3)**2 / 1000. - (x[2*i-2]-x[2*i-1]) + math.exp(20.*(x[2*i - 2]-x[2*i-1]))
        ce1 = 4*(x[0]-x[1])**2+x[1]-x[2]**2+x[2]-x[3]**2
        ce2 = 8*x[1]*(x[1]**2-x[0])-2*(1-x[1])+4*(x[1]-x[2])**2+x[0]**2+x[2]-x[3]**2+x[3]-x[4]**2
        ce3 = 8*x[2]*(x[2]**2-x[1])-2*(1-x[2])+4*(x[2]-x[3])**2+x[1]**2-x[0]+x[3]-x[4]**2+x[0]**2+x[4]-x[5]**2
        ce4 = 8*x[3]*(x[3]**2-x[2])-2*(1-x[3])+4*(x[3]-x[4])**2+x[2]**2-x[1]+x[4]-x[5]**2+x[1]**2+x[5]-x[0]
        ci1 = 8*x[4]*(x[4]**2-x[3])-2*(1-x[4])+4*(x[4]-x[5])**2+x[3]**2-x[2]+x[5]+x[2]**2-x[1]
        ci2 = -(8*x[5] * (x[5]**2-x[4])-2*(1-x[5]) +x[4]**2-x[3]+x[3]**2 - x[4])
        return [obj, ce1,ce2,ce3,ce4,ci1,ci2]
    def get_bounds(self):
        return ([-5]*6,[5]*6)
    def get_nic(self):
        return 2
    def get_nec(self):
        return 4
    def gradient(self, x):
        return pg.estimate_gradient_h(lambda x: self.fitness(x), x)


prob = pg.problem(my_constrained_udp())
xSol =[0.69366511, 0.77492458, 0.91588274, 0.93721851, 0.71253267,1.35350287]  # local optimum solution
print("local optimum:")
print(prob.fitness(xSol))

algo = pg.algorithm(pg.ihs(gen=2000))

pop = pg.population(prob, size=4, seed=1)  # for size < 4 pop.push_back works as expected. For size >=4 the new chamption is not recognised

print("before push_back")
print(pop.champion_f)
pop.push_back( xSol )  # this should be the new champion
print("after push_back")
print(pop.champion_f)

pop=algo.evolve(pop)
```

**Comment by darioizzo** [comment]
This is not a bug, its correct behaviour. 

The new individual you are adding is not 'better' than the current best, hence the champion is not updated.

The notion of 'better' in a constrained optimization setup is (in this order)

* number of constraint satisfied
* L2 norm of the constraint violation
* objective function

To control when a constraint is satisfied you should always set the ```c_tol``` constraint tolerance via the corresponding method of the problem. 

Please consider using the chat in gitter (https://gitter.im/pagmo2/Lobby) to ask these types of questions ... we then typically ask there to open issues in case.

**Comment by waldemar-martens** [comment]
Thanks for the clarification, Dario!
