### ISSUE TITLE
"b" parameter for population causes algorithm to stop

### ISSUE THREAD

**Issue by Tomalwo** [esa/pagmo2#378]
I have an issue with NSGAII (and maybe other algorithms) since the latest update. 
Before the update  to pagmo 2.12.0, I was using this code, which worked fine:

```
pop = pg.population(prob = problem, size = pop_size, seed = seed)
pop = algo.evolve(pop)
```

After the update, there was a problem with pg.population, so I changed it to this (adding the b parameter):

```
pop = pg.population(prob = problem, size = pop_size, b = None, seed = seed)
pop = algo.evolve(pop)
```

But now the algorithm stops after the population step. 
Probably I'm doing something wrong, so any suggestions are appreciated.

**Comment by bluescarni** [comment]
Could you provide more information on what is exactly happening?

> After the update, there was a problem with pg.population

What kind of problem precisely?

> But now the algorithm stops after the population step.

What does it mean that it stops? Is it crashing? Also, what kind of operating system and installation method for pygmo are you using?

**Comment by Tomalwo** [comment]
Hi Francesco,

I'm running Python 3.66 (64 bit) on Windows 10 (using Visual Studio). I've used pip to install pygmo.

The problem is that, after the first generation is calculated, the program keeps churning without any apparent progress / function evaluations. (I just get a blinking dash in the console.)

So there's no obvious mistake in the code I posted?

Thanks!

Thomas

________________________________

**Comment by bluescarni** [comment]
@Tomalwo there are known issues with the Windows pip packages, see for instance #358. Could you try with the conda packages instead?

**Comment by Tomalwo** [comment]
@bluescarni Happy New Year! I've installed Pygmo with conda, but am having trouble installing other pip packages that I need (pyomo, rbfopt). (I'm using Minicoda3 on Windows 10, and it's troublesome.)

**Comment by bluescarni** [comment]
> @bluescarni Happy New Year!
> 
> I've installed Pygmo with conda, but am having trouble installing other pip packages that I need (pyomo, rbfopt). (I'm using Minicoda3 on Windows 10, and it's troublesome.)

pyomo seems to be available in conda via conda-forge (like pygmo), so you should not need to use pip to install it. I don't see any conda package for rbfopt though. Are you using conda's pip?

> Would it be possible to also make the previous version of Pygmo available for pip? That one worked for me.

The previous version of pygmo have not been removed. You can install them via ``pip`` using the syntax for installing specific package versions:

https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

I would suggest you to try to make the conda installation work though, I would not trust pygmo's Windows pip packages.

**Comment by bluescarni** [comment]
I will close the report for the time being as it seems related to the Windows pip issues reported elsewhere. Please re-open if needed.
