### ISSUE TITLE
Population object does not have `compute_pareto_fronts` method

### ISSUE THREAD

**Issue by Nick-Hemenway** [esa/pagmo2#386]
I am new to Pygmo and am trying to use it for multiobjective optimization of electric machines. After creating and evolving a population, I want to extract and plot the pareto front. The documentation for the population class located [here](https://esa.github.io/pygmo/documentation/population.html?highlight=plot#PyGMO.population.plot_pareto_fronts) says that there is a `compute_pareto_fronts` method, however, when I try to do this, I get an error saying that no such method exists. I am using Pygmo version 2.12.0.

**Comment by darioizzo** [comment]
You are reading the documentation of the old pagmo 1.x project. The docs for pagmo2, which is this GitHub repo, have a different URL. You can find it on the readme of the GitHub page.

In pygmo2 plot pareto front is no longer a method of population, rather and if I am not mistaken, a stand alone function.
