### ISSUE TITLE
Algorithm step 

### ISSUE THREAD

**Issue by jamesbut** [esa/pagmo2#396]
I am using pagmo2 in a project and it has been really helpful so thank you to all the developers.

However, for my project it is important to render the best solution at each generation. This is currently unavailable in the current implementation because the algorithm API dictates a method 'evolve' which evolves the population until completion. In this case, I can only get access to the best solution before or after the entire evolutionary run has been carried out (I have been using CMAES for reference).

I was wondering whether a nice feature would be to include a single optimisation step function (for example, for one generation in an evolutionary algorithm) such that one can analyse or render between these calls?

**Comment by bluescarni** [comment]
I believe that most algorithms (including CMAES) allow you to set the number of generational steps that are performed in an ``evolve()`` call. Thus, an option for you would be to set a single generational step when constructing a CMAES object, and then you will be able to check the population state step-by-step at the end of each ``evolve()`` call.

As a caveat, I think that for some algorithms an ``evolve()`` with ``n`` generations is equivalent to ``n`` ``evolve()`` with 1 generation, but for others that is not the case. Pinging @darioizzo as he knows better the subject than myself.

**Comment by darioizzo** [comment]
@bluescarni That is correct, but those algorithms usually have a memory kwarg that can be set to True and that allows to recover the equivalence.

**Comment by jamesbut** [comment]
@bluescarni yes that is the case for some algorithms, but for algorithms with memory it is not, for example: CMAES. 

@darioizzo Thank you, I had not seen the memory argument before - this is exactly what I need :)
