### ISSUE TITLE
Question: How to constrain decision variables to integer values

### ISSUE THREAD

**Issue by jasperwolfhagen** [esa/pagmo2#399]
Dear,

I'm applying the MOEA's for solving collision avoidance problems and limiting the search space to integer values for the epoch of thrusting would significantly reduce computational effort (decision variables: [epoch of thrusting, delta Vx, delta Vy, deltaVz]) . 

I read through the documentation and issues, but saw no description of this utility. How would you suggest to implement this feature in my optimisation? Is there a built-in utility available?

Kind regards,

**Comment by bluescarni** [comment]
pagmo does support the definition of mixed-integer problems, but we currently have only a handful of algorithms capable of solving these types of problems. As far as I remember (pinging @darioizzo), algorithms which do not directly support integer programming will try to solve mixed-integer problems via relaxation.

So no, there's currently no way to constrain variables to integer values using MOEA/D.

**Comment by jasperwolfhagen** [comment]
Thank you for the quick reply!

**Comment by jasperwolfhagen** [comment]
I wrote a few lines in the header file of my problem (self-written UDP), see below. The first generation only integer values are assumed for the last decision variable, but in the second generation the algorithm (MOEA/D) again takes decimal values for the decision variable. Is there no work-around to keep it producing only integer decision variables?

std::vector<double>::size_type get_nix() const
{
        return 1;
}

**Comment by yezhengli-Mr9** [comment]
> pagmo does support the definition of mixed-integer problems, but we currently have only a handful of algorithms capable of solving these types of problems. As far as I remember (pinging [@darioizzo](https://github.com/darioizzo)), algorithms which do not directly support integer programming will try to solve mixed-integer problems via relaxation.
> 
> So no, there's currently no way to constrain variables to integer values using MOEA/D.

PSO support mix-integer in case 4 out of 20 variables are integer?

set within problem for PSO
```cpp
vector_double::size_type tscall::get_nix() const{
    return m_nix;
}
```
Any possible start-up code I can refer to? Then I may develop PSO into mixed-integer.
