### ISSUE TITLE
Split pygmo compilation

### ISSUE THREAD

**Issue by bluescarni** [esa/pagmo2#40]
As we keep on adding functionality, pygmo compilation becomes more expensive both in terms of runtime and memory usage. We should split up ``core.cpp`` in separate parts in order to curb memory usage and allow to recompile only the parts that actually need to be recompiled.

Note that we have to take care of additional NumPy initialization complexity when we split the module:

http://docs.scipy.org/doc/numpy/reference/c-api.array.html#importing-the-api

**Comment by darioizzo** [comment]
Is this going to be a problem only for the CI?
At the moment all my machines do not run into troubles.

**Comment by bluescarni** [comment]
It's taking about 4GB of memory for a debug build of pygmo, which I believe is getting close to travis' limit. There's also the fact that every change apart from the docstrings triggers a full rebuild, making it harder to debug as it takes quite a while to compile.

Now that pagmo is header only, changes in the core c++ bits are anyway going to trigger a full rebuild in many cases, but at least the exposition bits I believe could benefit from some splitting up.

**Comment by bluescarni** [comment]
Fixed in #55.
