### ISSUE TITLE
Topologies should tell you more details

### ISSUE THREAD

**Issue by CoolRunning** [esa/pagmo2#401]
``` 
t = pg.topology(pg.topologies.ring(100))
```
gives you a nice object that you can print out to learn more. However, it would be nice to have some methods that return you graph-related bits of information. For now I propose:

* `t.number_of_edges()`
returns number of edges (in this example: 200)

* `t.number_of_nodes()`
returns number of nodes (100)

* `t.degree(k)`
return the degree of node `k` (in this example: 2)

The syntax of these methods is inspired by [NetworkX](https://networkx.github.io), one of the well known network libraries in Python.

While these methods are meant to deliver some basic information for C++, on the Python-side of things, something like

`G = t.to_networkx()`

Could be a very convenient interface (introducing a dependency on networkx though somewhat).

**Comment by bluescarni** [comment]
This is now being worked on in pygmo esa/pygmo2#34

**Comment by bluescarni** [comment]
esa/pygmo2#34 has been merged. pagmo/pygmo 2.15 will feature topology export/import from Boost Graph (C++) and NetworkX (Python).

Closing this one.
