### ISSUE TITLE
Make CEC2014 (and other data-heavy features) available on Windows

### ISSUE THREAD

**Issue by CoolRunning** [esa/pagmo2#404]
Currently, the problem suite CEC2014 is not available on Windows. Reason for that is the heavy reliance on large scale data, which needs to be encoded as static arrays. Parsing those arrays with compilers on Windows is difficult, so new workarounds need to be put into place.

This could also improve situations, where large chunks of numerical data are needed for testing (i.e. hypervolume computations).

**Comment by bluescarni** [comment]
This is now implemented in #412.

**Comment by bluescarni** [comment]
Closed by #412.
