### ISSUE TITLE
Question: get_nix function

### ISSUE THREAD

**Issue by jasperwolfhagen** [esa/pagmo2#406]
Dear,
I've tried to apply a get_nix function to set the number of integer decision variables of my UDP. This works perfectly for the first generation. However, after the first generation the individuals start having non-integer elements randomly (some have integer elements and some do not and this varies over individuals). 

I have two questions:
- The algorithm does not support Integer programming, is this the reason for this functioning?
- Can this be changed by altering a few lines in the algorithm class locally to generate integer rather than doubles?

Thank you for all the great work on Pagmo,
Jasper

**Comment by darioizzo** [comment]
* Yes. If the algorithm does not support integer programming he will act on the integer part of the crhomosome with his float operators.

* Yes. Depending on the algorithm, of course.

Its an intended case (relaxation) and for sme integer problems can be a good approach.
