### ISSUE TITLE
get the Island caller inside the fitness function 

### ISSUE THREAD

**Issue by Alblahm** [esa/pagmo2#417]
I've created a simple working problem to show you my question, the real one is harder to solve.

 This sample is a simple task that minimizes a cuadratic funcion of two coeficients, but i've another one that is much more hard and should be launched in a computation cluster, so I need to identify the callers of the fitness function (the island id or smth similar) with that id I can send the resolution of the fitness to each node of the computation cluster.

 Inside the definition of the problem struct, I need to know, on each iteration of the algorithm what is the island that is calling the fitness funcion. Is it posible to get the id of that island ???

```
int main()
{
    problem problemaPend{problem_CIRCUITO()};
    algorithm algoritmoAjuste{cmaes(10, -1, -1, -1, -1, 0.5, 1e-6, 1e-6, false, true)}; 
    archipelago archiIslas{1u, algoritmoAjuste, problemaPend, 14u};
    archiIslas.evolve(200);
}
```

```
struct problem_CIRCUITO {
    std::vector<double> fitness(const std::vector<double>  &dv) const
    {
   ///*************************************************
             int ID_ISLAND = SOME_FUNTION ???? 
   /// *************************************************
  
	int dimProb=dv.size();
        std::vector<float> dVal(dimProb,0);
        dVal.assign(dv.begin(),dv.end());

        // Simulate the solver . ...  
        double SetAreaObj = 0;
        double sumArea = std::fabs(((dv[0] * dv[0] + (dv[1]-2) * (dv[1]-2)) - SetAreaObj));
        double sumArea = std::fabs(((4 * dVal[1] * dVal[0]/3 - 1e-2*dVal[2] - 1e-2*dVal[3]- 1e-2*dVal[4]) - SetAreaObj));
        return {sumArea};
    } 
    std::pair<std::vector<double> , std::vector<double> > get_bounds() const
    {
        return {{0.,0.}, {10.,10.}}; 
    }
};
```

 Thanks in advance ...

**Comment by bluescarni** [comment]
You cannot get directly the ID of an island from within an objective function, because a problem has no knowledge about whether it "lives" inside an island or not.

What you can do however is to add an attribute to your ``problem_CIRCUITO`` struct, e.g.,

```c++
struct problem_CIRCUITO {
  // ...
  int m_ID;
};
```

Then you can create an empty archipelago and add islands to it one at a time. You can construct each island passing in a ``problem_CIRCUITO`` instance created with a different ``m_ID``, and from within the objective function you can access the ``m_ID`` attribute of your problem.

**Comment by Alblahm** [comment]
Thanks, I just did that, and it worked ... I've created a circuit, added the private member string attribute and also add a setter function, then in the main

```
main()
{
   // ...
   problem_CIRCUITO prob_Comunidad{};
   prob_Comunidad.set_LogFile("nameLog.txt"); 
  //...
}
```


```
struct problem_CIRCUITO {
   void set_LogFile(std::string nArchivo)
   {
   archDatos = nArchivo;
   }
private:
   std::string archDatos = "archP.log";
};
```

  Thanks ...
