### ISSUE TITLE
Adding a starting sol to the population ...

### ISSUE THREAD

**Issue by Alblahm** [esa/pagmo2#418]
Is there any place in the documentation on how to add an individual to the population of one island that holds a solution that is near of the solution of the problem ?, just to help the algorithm to converge faster to the solution.
My problem finds out a 4 elements vector [a,b,c,d] that minimizes a function, and the solution I want to add is something like:
 [2.3, 4.2 ,0 .3, 5.0]; 
It should be near the minimum so I can help the algorithm to reach faster the N-dimensional place of the solution. (Of course this is not the minimum but should be near).

```
   //  Instantiate a pagmo problem constructing it from a UDP  
    problem problemaPend{prob_Comunidad}

    //  Instantiate a pagmo algorithm
    algorithm algoritmoAjuste{cmaes(10, -1, -1, -1, -1, 0.5, 1e-6, 1e-6, false, true)}; 

    //  Instantiate an archipelago with 1 island having each 30 individuals.
    archipelago archiIslas{1u, algoritmoAjuste, problemaPend, 30u}

   **** How do I add here an inidvidual with the sol ***

    //  Run the evolution in parallel on the 16 separate islands 10 times.
    archiIslas.evolve(20);
```

 Thanks in advance ...

**Comment by bluescarni** [comment]
@Alblahm You can manipulate the island's population. E.g., something like this:

```c++
auto pop = archiIslas[0].get_population();
// Add/remove/modify individuals using the population API...
// ...
archiIslas[0].set_population(pop);
```

For modifying ``pop``, see functions such as ``push_back()``, ``set_x()``, ``set_xf()``, etc. from the docs:

https://esa.github.io/pagmo2/docs/cpp/population.html

**Comment by Alblahm** [comment]
Thanks, it worked ... just add one individual, and it evaluates it as soon as it starts the evolution steps...

```
	auto popIsla = archiIslas[0].get_population();
	popIsla.push_back({34,-8});
```
