### ISSUE TITLE
Duplicated implementations of SBX and polynomial mutations

### ISSUE THREAD

**Issue by MLopez-Ibanez** [esa/pagmo2#419]
The implementations of NSGA2 and SGA have their own implementations of SBX and polynomial mutations. Are these the same? If so, why the duplication?

Same goes for MOEA/D and NSGA2 regarding polynomial mutation.

**Comment by bluescarni** [comment]
@MLopez-Ibanez I'll let @darioizzo reply in more detail, but the gist is that pagmo is not currently meant to be a framework for building algorithms, so we haven't given much thought so far to exposing/re-using implementation details of algorithms.

Of course, I agree that it would be better to avoid the duplication, even only from a software engineering standpoint. @darioizzo do you think we can get this done for the next release?

**Comment by MLopez-Ibanez** [comment]
> Of course, I agree that it would be better to avoid the duplication, even only from a software engineering standpoint. @darioizzo do you think we can get this done for the next release?

As shown in bug #421, at least the implementation of SBX is buggy, and it is duplicated all over the place (I have only looked at the NSGA2 one, so not sure if others have the same problems).

I only found out this because I had to reimplement SBX in pure python to use it in my UDA for pygmo2.

**Comment by bluescarni** [comment]
> As shown in bug #421, at least the implementation of SBX is buggy, and it is duplicated all over the place (I have only looked at the NSGA2 one, so not sure if others have the same problems).

The best course of action seems to be to factor out these operators as public functions and fix their issues in the process. But I am not familiar with this part of the code, so it would be best if @darioizzo took charge.

**Comment by darioizzo** [comment]
sure, np.

**Comment by darioizzo** [comment]
I would suggest to add in ``utils`` a new header/cpp file called ``genetic_operators`` where to move all said implementations.

**Comment by bluescarni** [comment]
Fixed by #422.
