### ISSUE TITLE
Biased random coin tosses

### ISSUE THREAD

**Issue by MLopez-Ibanez** [esa/pagmo2#420]
In many places, the code implements a random coin toss as:

```c++
if (drng(m_e) <= p) // Do something
```
However, as `drng()` returns a value in `[0,1)`, using `<=` slightly biases the probability towards true. It is easy to see it in the extreme case when  `p = 0`, then we should never do something, however, the above condition may still be true. I believe the correct code should be:

```c++
if (drng(m_e) < p) // Do something
```
then with `p = 0`, we never do something and with `p=1` we always do something.

There are many examples of the above pattern: 
https://github.com/esa/pagmo2/blob/ab1f3a945a4b78886bb270532d80215f08782a3a/src/algorithms/nsga2.cpp#L391

**Comment by bluescarni** [comment]
Fixed by #422.
