### ISSUE TITLE
[Question] Does pagmo2 support building static libraries?

### ISSUE THREAD

**Issue by Balandat** [esa/pagmo2#423]
Looks like pagmo does: https://github.com/esa/pagmo/blob/master/src/CMakeLists.txt#L246-L247, but I haven't seen similar flags / settings for pagmo2.

**Comment by bluescarni** [comment]
@Balandat not currently, but it wouldn't be difficult to add support for it in the build system. What is your use case for building pagmo as a static library?

**Comment by Balandat** [comment]
The use case is that static libraries make it easier to deploy binaries to a fleet of machines.

**Comment by Balandat** [comment]
FWIW replacing `SHARED` with `STATIC` in https://github.com/esa/pagmo2/blob/master/CMakeLists.txt#L259 seems to build just fine.

**Comment by bluescarni** [comment]
> FWIW replacing `SHARED` with `STATIC` in https://github.com/esa/pagmo2/blob/master/CMakeLists.txt#L259 seems to build just fine.

Yes, that's basically all that is needed in practice (we should also change the meaning of the ``PAGMO_DLL_PUBLIC`` and similar definitions to expand to nothing when pagmo is being built as a static library).

I'll open a PR and make sure this is available in the next pagmo version.

**Comment by Balandat** [comment]
Great, thanks. Ideally there would be an additional `BUILD_STATIC`flag to cmake that would result in building both the shared and static libs.

**Comment by bluescarni** [comment]
I'd be oriented towards making an exclusive choice between a shared or static library build. Do you need both versions at the same time?

**Comment by bluescarni** [comment]
PR up at #426.

**Comment by bluescarni** [comment]
@Balandat any comment on #426 before I merge it?

**Comment by Balandat** [comment]
No I think this looks good to me, thanks for adding the option.

**Comment by bluescarni** [comment]
Closed via #426.
