### ISSUE TITLE
Bug in the NSPSO test case

### ISSUE THREAD

**Issue by bluescarni** [esa/pagmo2#427]
Here:

https://github.com/esa/pagmo2/blob/master/tests/nspso.cpp#L173

``std::all_of()`` is invoked, but its result is not checked by a ``BOOST_CHECK()`` statement. If one adds the ``BOOST_CHECK()``, then the test fails.

@darioizzo would you mind taking a look?

**Comment by bluescarni** [comment]
Pinging @Sceki as well.

**Comment by darioizzo** [comment]
I think that test was, in @Sceki mind, supposed to test that NSPSO would work on integer problems. But I do not think that NSPSO is, infact its marked as M-U. So I would say the test is to be removed altogether.

**Comment by bluescarni** [comment]
Ok, I ditched the test in #426.

**Comment by Sceki** [comment]
> I think that test was, in @Sceki mind, supposed to test that NSPSO would work on integer problems. But I do not think that NSPSO is, infact its marked as M-U. So I would say the test is to be removed altogether.

Indeed.. sorry about that!
