### ISSUE TITLE
Installation Error in Ubuntu 16.04

### ISSUE THREAD

**Issue by sc1101** [esa/pagmo2#429]
Hello! I met a problem when installing pagmo2 in Ubuntu 16.04.

I followed the guidance in the document and downloaded the source code using:
`git clone https://github.com/esa/pagmo2.git`
Then, I creade a folder named 'build', entered in it and successfully executed the command:
`cmake ../ -DPAGMO_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=~/.local`
However, I failed in the next step:
`cmake --build .`
throwing the error showing in the following screenshot:
![image](https://user-images.githubusercontent.com/60003504/80936638-9b048700-8e04-11ea-9fdb-036b4c20a517.png)

My gcc version is 9.2.0, cmake is 3.17.0 and I am sure that I have installed Boost 1.60 as well as Intel TBB.
I am quite confused now and don't know how to address it. Can you help me? Thanks a lot!

**Comment by darioizzo** [comment]
As a quick workaround you can use conda package manager and install the pagmo-devel package on some environment.

It seems something is off in Ubuntu when looking for boost serialization and unit test libraries ...

Since the libpagmo.so is created correctly, could you find it and type, in the same directory:
```
ldd libpagmo.so
```
and post here the output ?

**Comment by bluescarni** [comment]
@sc1101 could you also post the full CMake output, and the output of ``make VERBOSE=1``? You can use https://gist.github.com/ if there's too much text to paste here.

**Comment by sc1101** [comment]
Thank you very much! I have reinstalled the linux system and tomorrow I will try it again.

**Comment by sc1101** [comment]
Thanks for help! I make it. Then I want to open another issue to get further help about how to run NSGA2 in pagmo2.
