### ISSUE TITLE
Confusing about archipelago::evolve()

### ISSUE THREAD

**Issue by sc1101** [esa/pagmo2#430]
Hello! When I read the 'Quick Start' of the document, I am confused with the step 4:

`// 4 - Run the evolution in parallel on the 16 separate islands 10 times.`
`archi.evolve(10);`

When I want to set only a group of individuals (meaning that there is no multi-population), then how to set the 'n' in the step 4? For example:
![image](https://user-images.githubusercontent.com/60003504/81037002-c4d8af00-8ed3-11ea-8302-a191e91796da.png)

If I let the 'n' be equal to 1 in the step 4: 
`archi.evolve(1);`
the optimal result I finally get would be very bad.

I have tried to read the source code of ' archipelago::evolve()', however, I am still confusing with it.

I am looking forward to your reply, thanks!

**Comment by darioizzo** [comment]
Please do not open issues on questions about the code use. We have the gitter chat where you can find some support for the correct use of pagmo.

On your question, if you only have one population, then you do not need an archipelago. Just use the evolve method of the algorithm directly. If you then want the single individual fitness to be evaluated in parallel you need to use a batch fitness evaluator. See docs.
