### ISSUE TITLE
Unable to compile under Archlinux - Imported target "Boost::boost" includes non-existent path

### ISSUE THREAD

**Issue by analca3** [esa/pagmo2#440]
**Describe the bug**
After CMake configuration I get

```
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "Boost::boost" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "Boost::boost" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.


```

**To Reproduce**
`yay -S pagmo`

**Expected behavior**
It gets compiled without errors. 

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Installation method: AUR package
 - Version: Completely updated

**Additional context**
A friend with a fresh installation of ArchLinux could install it without any problem. I assume it's a problem in my system but I'm not a CMake user so I don't know how to deal with this. I understand the problem but I have no idea why it "finds" Boost in `/include` instead of `/usr/include`. I reinstalled boost without luck. None of the points CMake say are applicable to me, I think.

Many thanks for the package and the support.

**Comment by darioizzo** [comment]
This is not a bug, rather a user problem. Removed the bug label.
