### ISSUE TITLE
Question about mp_island

### ISSUE THREAD

**Issue by scawsome** [esa/pagmo2#443]
Hello, I am applying your very nice package to a single objective optimization problem, where the computation of the objective function is expensive. As such I'd like to be able to use multiprocessing to speed up the optimization by dividing up a single population and evolving the individuals separately. I've run the following code as an example
```

import numpy as np
import pygmo as pg

if __name__=='__main__':
    isl = pg.island(algo = pg.pso(20000),
                    prob = pg.ackley(5),
                    size = 2000,
                    udi=pg.mp_island())

    print(isl.get_population().champion_f)
    print(isl.get_population().champion_x)
    print('running evolution')
    isl.evolve()
    isl.wait_check()
    print(isl.status)
    print(isl.get_population().champion_f)
    print(isl.get_population().champion_x)
```
and I observe that there is an initial spike in CPU usage but then it goes back to using a small percentage of the CPU resources
![dfg](https://user-images.githubusercontent.com/24279776/89668006-5f150e00-d89a-11ea-8c3c-45c5b824f74e.png)

Is this expected behavior or am I missing something? I have also tried running it with my complex/expensive calculation and it displays similar behavior (maxing out CPU usage at the beginning and then flattening out at a low percentage).

Any help with this would be much appreciated.
Thanks!

**Comment by Ajaja** [comment]
You need to use an archipelago to utilize all your 16 logical processors.

**Comment by scawsome** [comment]
Looks like I need to use the Archipelago framework to use parallel resources.
