### ISSUE TITLE
[BUG] SADE will not refuse to evolve a integer problem

### ISSUE THREAD

**Issue by callejon97** [esa/pagmo2#444]
**Describe the bug**
I am trying to solve an integer UDP, which contains, among others, the following methods, and is thus implemented as an Integer problem.

```py
class TSP():
    def get_ncx(self):
        return 0     
    def get_nix(self):
        return self.dim   
```
```py
    Problem name: Traveling Salesman Problem
    C++ class name: pybind11::object

    Global dimension:            533
    Integer dimension:            533
    Fitness dimension:            1
    Number of objectives:            1
    Equality constraints dimension:        0
    Inequality constraints dimension:    0
    Lower bounds: [0, 0, 0, 0, 0, ... ]
    Upper bounds: [532, 532, 532, 532, 532, ... ]
    Has batch fitness evaluation: false

    Has gradient: false
    User implemented gradient sparsity: false
    Has hessians: false
    User implemented hessians sparsity: false

    Fitness evaluations: 0

    Thread safety: none
```
The population is initialized correctly, with integers. When evolving the population using `algo.evolve(pop)`, Self-adaptive Differential Evolution (SADE) algorithm will update the population and convert them into floats.

**Expected behavior**
It is expected that the algorithm SADE will refuse to work with an integer problem and throw an exception into the user, as it is not meant to work with integer problems.

**Environment (please complete the following information):**
 - OS: Linux
 - Installation method: conda
 - Version: 2.15.0

**Comment by bluescarni** [comment]
I believe the default behaviour in pagmo is not to error out in such circumstances, under the assumption that it might be meaningful to try to resolve the problem by relaxation. Pinging @darioizzo .

Most of the core devs are on vacation, replies may be sluggish for a couple of weeks.

**Comment by darioizzo** [comment]
That was correct @bluescarni . For all algorithms that are not marked as able to solve integer problems, the default behaviour is to relax the problem and treat it as if the chromosome was made of double. This allows for a straight forward implementation of a relaxation approach.
