### ISSUE TITLE
[FEATURE] Adding pagmo2 to vcpkg

### ISSUE THREAD

**Issue by dmillard** [esa/pagmo2#446]
**Is your feature request related to a problem? Please describe.**
There is no pagmo2 package description in the vcpkg package manager.

**Describe the solution you'd like**
Pagmo installable as a source dependency through vcpkg.

**Additional context**
I have started a pull request against vcpkg to package pagmo2: https://github.com/microsoft/vcpkg/pull/13339
It seems there are now some nontrivial decisions to make (see https://github.com/microsoft/vcpkg/pull/13339#issuecomment-692520375) since `PAGMO_BUILD_STATIC_LIBRARY` was added recently, we can either patch the static build rules back to 2.15 or we can include a nonreleased HEAD ref in vcpkg for the time being.

Is someone from the pagmo team willing to weigh in on this? Is there a new release of pagmo planned soon? Thanks for any information you can provide.

**Comment by bluescarni** [comment]
@dmillard thanks for taking the lead on this.

A new pagmo release is due, but it's unclear when it's going to happen because at the moment we are swamped with another project, at least for the next few weeks. The PR that added static library support is here:

https://github.com/esa/pagmo2/pull/426

Perhaps for the time being you can try to extract the relevant bits from the diff?

**Comment by dmillard** [comment]
@bluescarni thanks very much for the quick reply.

I've patched out what I thought was relevant here: https://github.com/microsoft/vcpkg/pull/13339/commits/1dfb89963a67ebc8e70b1f2a734c2895ea2b75b2

Looks like there may be more work required for windows, but it's a start. I'll investigate.

Thanks again.

**Comment by bluescarni** [comment]
@dmillard pagmo 2.16.0, which includes the option to build as a static library, has been out for a while. Is there any progress on this? Anything we can do to help?

**Comment by dmillard** [comment]
Hi @bluescarni - unfortunately this PR fell off of my radar because I stopped using `vcpkg` for my active project. As you can see https://github.com/microsoft/vcpkg/pull/13339 got stuck in automated testing on x64 Windows.

I am still interested in getting this to work, however. Now that 2.16 is out I can try this again in a couple of days, and will start fresh from a clean 2.16 checkout. Thanks very much for the ping!

**Comment by dmillard** [comment]
Pagmo2 is now in vcpkg: https://github.com/microsoft/vcpkg/commit/a8a07972dbd6a835329f31133fb83b3f4723cb55

**Comment by darioizzo** [comment]
Thas fantastic news! Thanks a lot for this.

**Comment by bluescarni** [comment]
Thanks a lot @dmillard ! Would it be too much to ask for a PR adding a couple of lines to the docs about how to install using ``vcpkg``? I'd do it myself, but I have zero experience with ``vcpkg`` :)

**Comment by bluescarni** [comment]
-> https://github.com/esa/pagmo2/blob/master/doc/sphinx/install.rst#packages this would be the section

**Comment by SpaceIm** [comment]
Would it be possible to import some of the patches in this port into pagmo2 master branch?

It would be nice to not have to maintain this patch in package managers supporting Visual Studio, like vcpkg or conan: https://github.com/microsoft/vcpkg/blob/master/ports/pagmo2/disable-md-override.patch
An other patch I see in vcpkg port could be removed, if pagmo2 could provide an option to disable warnings as errors (-Werror or /WX for msvc).

**Comment by bluescarni** [comment]
> Would it be possible to import some of the patches in this port into pagmo2 master branch?
> 
>     * It would be nice to not have to maintain this patch in package managers supporting Visual Studio, like vcpkg or conan, since it's clearly wrong to override vc runtime requested by downstream projects: https://github.com/microsoft/vcpkg/blob/7c55ecac266fc3e554bc315053dc45c11ec811af/ports/pagmo2/disable-md-override.patch
> 
>     * An other patch I see in vcpkg port could be removed (https://github.com/microsoft/vcpkg/blob/7c55ecac266fc3e554bc315053dc45c11ec811af/ports/pagmo2/disable-C4701.patch), if pagmo2 could provide an option to disable warnings as errors (no -Werror or /WX for msvc, package managers don't like those flags since old versions tend to break with new compilers for no good reason).

These two patches are now in ``master`` and they will be part of the upcoming 2.18 release.

@dmillard anything we can do to warn the vcpkg maintainers that those patches will soon be obsolete?
