### ISSUE TITLE
[BUG] Minimal example of MOO crashes under Windows 10 with error code 0xC0000005

### ISSUE THREAD

**Issue by SamKlier** [esa/pagmo2#449]
**Describe the bug**
Unhandled exception at 0x0000000066B8FFCA (libpagmo.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000017761BF85F8.

**To Reproduce**
I ran this minimal example on Windows 10:
```
import pygmo as pg

prob = pg.problem(pg.zdt(1))
alg = pg.algorithm(pg.moead(gen=5))
pop = pg.population(prob, 40)
print("???")
pop = alg.evolve(pop)
print("!!!")
pop.plot_pareto_fronts()
```
The script will print ??? but not !!!. I tried moead and nsga2 as algorithms. Both are not working.
It crashes somewhere down below in alg.evolve with 0xC0000005. The same script is running fine at an ubuntu machine.

Visual Studio Debugger tells me:
Unhandled exception at 0x0000000066B8FFCA (libpagmo.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000017761BF85F8.

**Environment (please complete the following information):**
 - OS: Windows 10 1909 | 18363.959
 - Installation method: fresh Anaconda environment with Python 3.7, pygmo installed via pip
 - Version: 2.13.0, 2.11.4

**Additional context**
`pip install pygmo` gives me 2.13.0 as the newest version available.

**Comment by CoolRunning** [comment]
I just tried on my windows. Cannot reproduce. Why do you install pygmo with pip? Give it a try with conda itself

`conda install pygmo`

it will give you a newer version as well (I have 2.15.0 right now).

**Comment by SamKlier** [comment]
Good questions...why we install it over pip...
Anyway:
`conda install pygmo`
Does not work. Now I used:
`conda install -c conda-forge pygmo`
This gives me pygmo 2.15.0 and now it works (again)!

Thank you very much.

**Comment by bluescarni** [comment]
@SamKlier the Windows pip packages have known issues, and we have discontinued them due to lack of manpower. We recommend all Windows users to use conda instead.

**Comment by SamKlier** [comment]
I just wanted to ask if you could include that to your documentation. But hey, it's already there! (It hasn't been there a while ago as we installed pygmo first.) And it even includes an explanation:
[https://esa.github.io/pygmo2/install.html#pip](url)

Thanks for the work!
