### ISSUE TITLE
Documentation how to build Pagmo2 using local installed TBB, BOOST, Eigen (not system-wide)

### ISSUE THREAD

**Issue by erwincoumans** [esa/pagmo2#464]
Nice project, thanks!

Instead of system-wide installation, some projects have local installed versions of Eigen, BOOST and TBB etc.

```
ROOT=$(pwd)
cd third_party/eigen
#Build Eigen locally
mkdir build_cmake
cd build_cmake
cmake -DCMAKE_CXX_FLAGS="/MP" -DCMAKE_DEBUG_POSTFIX="" -DINSTALL_LIBS=ON -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX:PATH=local_install   ..
cmake  --build .  --target INSTALL  --config Release
#now Eigen install is in the local_install folder

cd $ROOT/third_party/oneTBB
#Build TBB locally
cmake -DCMAKE_INSTALL_PREFIX:PATH=local_install -DTBB_TEST=OFF ..
cmake  --build .  --target INSTALL  --config Release
#now TBB install (include/lib) is in the local_install directory

#Build BOOST locally
cd $ROOT/third_party/boost_1_69_0
bootstrap.bat
b2 install --prefix=local_install --toolset=msvc --build-type=complete --address-model=64 link=static  --with-thread   --with-serialization --with-test
#now BOOST installation (include, libs) are in the local directory.
```

Then you can tell cmake where to find the local installed versions:
```
git clone https://github.com/esa/pagmo2
cd pagmo2
mkdir build
cd build
cmake -DEigen3_DIR=$ROOT/third_party/eigen3/build_cmake/local_install   -DTBB_DIR=$ROOT/third_party/oneTBB/build_cmake/local_install -DBOOST_DIR=$ROOT/third_party/boost_1_69_0/local_install ..
```

**Is your feature request related to a problem? Please describe.**
Can't build Pagmo2, it doesn't find Eigen, BOOST or (one)TBB

**Describe the solution you'd like**
A clear and concise description how to tell cmake where to find local Eigen, TBB and Boost installations preferably using the common -D<lib>_DIR=location method (-DEigen_DIR=...), BOOST (-DBOOST_DIR=...), TBB (-DTBB_DIR=...)

(let's ignore about oneTBB versus TBB for now, it has its own [issue](https://github.com/esa/pagmo2/issues/463))

**Comment by erwincoumans** [comment]
The cmake/pagmo2 'find' doesn't manage to find things. Deleting all the logic and replacing by this works, including [oneTBB](https://github.com/esa/pagmo2/issues/463)

```
target_include_directories (pagmo  PUBLIC  ${CMAKE_CURRENT_LIST_DIR}/../boost_1_69_0)
target_include_directories (pagmo  PUBLIC  ${CMAKE_CURRENT_LIST_DIR}/../oneTBB/include)
target_link_directories (pagmo  PUBLIC  ${CMAKE_CURRENT_LIST_DIR}/../boost_1_69_0/lib)
target_link_directories (pagmo  PUBLIC  ${CMAKE_CURRENT_LIST_DIR}/../oneTBB/build/msvc_19.28_cxx_64_md_debug)
add_library (eigen INTERFACE)
add_library (Eigen3::Eigen ALIAS eigen)
#target_compile_definitions (eigen INTERFACE ${EIGEN_DEFINITIONS})
target_include_directories (eigen INTERFACE
   ${CMAKE_CURRENT_LIST_DIR}/../eigen3
)
set(Eigen3_FOUND TRUE)
```

**Comment by erwincoumans** [comment]
I tried

**Comment by erwincoumans** [comment]
pagmo did find the Boost includes, but it didn't find the libraries in the libs folder. How can you point to the Boost library folder? (all possible versions of the libs are in there)

**Comment by bluescarni** [comment]
> pagmo did find the Boost includes, but it didn't find the libraries in the libs folder. How can you point to the Boost library folder? (all possible versions of the libs are in there)

My best guess is that CMake is trying to use Boost's own CMake scripts, which are known to cause issues at this time. Can you try passing the option ``-DBoost_NO_BOOST_CMAKE=ON`` when you invoke CMake and see if it makes a difference?

> I can create a simple reproduction case with a script file that clones pagmo2, boost, eigen and oneTBB, see if we can make that work in a local folder?

This sounds similar to what we are already doing in the CI, where (in some builds) we install the dependencies via conda. In such a setup, CMake has to locate the dependencies in a non-standard prefix (i.e., not ``/usr`` nor ``/use/local``). See here for an example:

https://github.com/esa/pagmo2/blob/master/tools/circleci_bionic_gcc7_coverage.sh

It's not 100% clear to me however what the acitvation of the conda environment means exactly in terms of environment variables and how this helps CMake.

in any case, feel free to share the script here, so we can try to understand what is going on.

**Comment by erwincoumans** [comment]
Yes, I had a quick look at conda, but there is too much complexity/magic happening in that system.
Better to simply build Boost, oneTBB, Eigen and pagmo2 from source, explicitly, using cmake, and get that to work. I'll try to find time to share a script and hopefully we can sort it out.

**Comment by erwincoumans** [comment]
Finally got pagmo2 to compile with local installed versions, including the latest oneTBB

```
cmake -DPAGMO_WITH_EIGEN3=ON -DBoost_DIR:PATH=D:/dev/tds/pagmo2_example/third_party/boost/local/lib/cmake/Boost-1.76.0 -DEigen3_DIR:PATH=D:/dev/tds/pagmo2_example/third_party/eigen/build_cmake -DTBB_VERSION=2021.1.0 -DPAGMO_BUILD_STATIC_LIBRARY=ON ..
```

-DBoost_DIR:PATH=
Explicitly providing the TBB_VERSION will skip the error on file on oneTBB
-DPAGMO_BUILD_STATIC_LIBRARY=ON will prevent pagmo2 DLL and failing to find the tbb library. Leave it up to the user application to find the right onTBB library.


There are some padding warnings that are treated as errors. Disabling warnings as errors make it work (Removing /WX).

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	522	
Warning	C4701	potentially uninitialized local variable 'sum2' used	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	522	
Warning	C4701	potentially uninitialized local variable 'xx' used	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	1324	
Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	

```

**Comment by bluescarni** [comment]
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	522	
> Warning	C4701	potentially uninitialized local variable 'sum2' used	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	522	
> Warning	C4701	potentially uninitialized local variable 'xx' used	pagmo	D:\dev\tds\pagmo2_example\third_party\pagmo2\src\problems\cec2014.cpp	1324	
> Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Error	C2220	the following warning is treated as an error	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> Warning	C4324	'tbb::detail::d1::task': structure was padded due to alignment specifier	pagmo	D:\dev\tds\pagmo2_example\third_party\oneTBB\build_cmake\local_install\include\oneapi\tbb\detail\_task.h	233	
> ```

Thanks for reporting these, I'll make sure to add pragmas to ignore these warnings in the TBB headers.

Unfortunately it's hard for us to test debug builds on Windows because of the incompatibilities on that platform between debug and release runtimes.
