### ISSUE TITLE
Wrong release date of version 2.17.0

### ISSUE THREAD

**Issue by rowbotman** [esa/pagmo2#473]
**Describe the bug**
The last release (2.17.0) was in the 2021 year, but the date on the [site](https://esa.github.io/pagmo2/changelog.html#id2) is incorrect.

**To Reproduce**
1. Go to [change log page](https://esa.github.io/pagmo2/changelog.html#id2)
2. Check out date

**Expected behavior**
It should be 2021-03-05

**Comment by bluescarni** [comment]
Thanks for the report, this will be fixed in #479.
