### ISSUE TITLE
[BUG] Typo: This is a multiobjective "algortihm"

### ISSUE THREAD

**Issue by jschueller** [esa/pagmo2#489]
This typo "algortihm" is found in several classes, eg
https://github.com/esa/pagmo2/blob/master/src/algorithms/nsga2.cpp#L120

**Comment by bluescarni** [comment]
@jschueller Thanks for reporting, I'll make sure to fix the typos in the next version.

**Comment by bluescarni** [comment]
I think this was fixed in #518 , please re-open if needed.

**Comment by jschueller** [comment]
thanks
