### ISSUE TITLE
Move from inheritance to encapsulation for the metas

### ISSUE THREAD

**Issue by bluescarni** [esa/pagmo2#49]
After a discussion on gitter, it appears it may be more appropriate for meta algos/probs to encapsulate a ``problem``/``algorithm`` instance, instead of inheriting. The main advantages:

- instead of blacklisting methods we don't want to inherit, we whitelist (i.e, re-implement with one-line wrapper) methods we want. This seems a superior approach in our situation, as we are blacklisting lots of stuff;
- we remove the cognitive confusion of an inheritance relation that ultimately has no other purpose than sharing common code;
- we *may* be able to reduce the complexity of the Python bindings (but this part needs to be clarified better).

Disadvantages:

- if we add/modify functionality in ``problem``/``algorithm`` we need to iterate over all metas to adapt them (?).

**Comment by darioizzo** [comment]
This was done and "accepted" in #50
