### ISSUE TITLE
[BUG] ambiguous problem integer/continous components layout documentation

### ISSUE THREAD

**Issue by jschueller** [esa/pagmo2#496]
for integer problems, the documentation is unclear about how integer and continuous components must be distinguished:
https://esa.github.io/pagmo2/docs/cpp/problem.html#_CPPv4NK5pagmo7problem7get_nixEv

I figured out from the pygmo doc that integers must be tucked at the end after the continuous components:
https://esa.github.io/pygmo2/tutorials/coding_udp_minlp.html

I suggest to mention that in the get_nix method doc

**Comment by bluescarni** [comment]
Thanks for the report! I'll make sure this is fixed for the next version.
