### ISSUE TITLE
error when building pagmo2

### ISSUE THREAD

**Issue by Thaer83** [esa/pagmo2#498]
When executing this command (cmake --build .) the following error occurs.

<pre>[  1%] <font color="#4E9A06">Building CXX object CMakeFiles/pagmo.dir/src/islands/fork_island.cpp.o</font>
In file included from <b>/usr/include/boost/serialization/void_cast.hpp:29:0</b>,
                 from <b>/usr/include/boost/archive/detail/iserializer.hpp:79</b>,
                 from <b>/usr/include/boost/archive/detail/interface_iarchive.hpp:22</b>,
                 from <b>/usr/include/boost/archive/detail/common_iarchive.hpp:23</b>,
                 from <b>/usr/include/boost/archive/basic_binary_iarchive.hpp:30</b>,
                 from <b>/usr/include/boost/archive/binary_iarchive_impl.hpp:21</b>,
                 from <b>/usr/include/boost/archive/binary_iarchive.hpp:20</b>,
                 from <b>/home/thaer/pagmo2/include/pagmo/s11n.hpp:53</b>,
                 from <b>/home/thaer/pagmo2/include/pagmo/problem.hpp:52</b>,
                 from <b>/home/thaer/pagmo2/include/pagmo/bfe.hpp:48</b>,
                 from <b>/home/thaer/pagmo2/include/pagmo/population.hpp:39</b>,
                 from <b>/home/thaer/pagmo2/include/pagmo/algorithm.hpp:48</b>,
                 from <b>/home/thaer/pagmo2/src/islands/fork_island.cpp:49</b>:
/usr/include/boost/type_traits/is_virtual_base_of.hpp: In instantiation of ‘<b>struct boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::boost_type_traits_internal_struct_X</b>’:
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:80:5:</b>   required from ‘<b>const bool boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::value</b>’
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:88:4:</b>   required from ‘<b>const bool boost::detail::is_virtual_base_of_impl2&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;::value</b>’
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:97:45:</b>   required from ‘<b>struct boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/mpl/if.hpp:63:11:</b>   required from ‘<b>struct boost::mpl::if_&lt;boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_virtual_base&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_primitive&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt; &gt;</b>’
<b>/usr/include/boost/mpl/eval_if.hpp:37:41:</b>   required from ‘<b>struct boost::mpl::eval_if&lt;boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_virtual_base&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_primitive&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt; &gt;</b>’
<b>/usr/include/boost/serialization/void_cast.hpp:279:17:</b>   [ skipping 15 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
<b>/usr/include/boost/serialization/export.hpp:86:1:</b>   required from ‘<b>struct boost::archive::detail::ptr_serialization_support&lt;boost::archive::binary_iarchive, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/archive/detail/register_archive.hpp:25:8:</b>   required from ‘<b>struct boost::archive::detail::_ptr_serialization_support&lt;boost::archive::binary_iarchive, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/archive/binary_iarchive.hpp:57:1:</b><b>   required by substitution </b>of ‘<b>template&lt;class Serializable&gt; typename boost::archive::detail::_ptr_serialization_support&lt;boost::archive::binary_iarchive, Serializable&gt;::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::binary_iarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;]</b>’
<b>/usr/include/boost/serialization/export.hpp:123:38:</b>   required from ‘<b>void boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;::export_guid(mpl_::false_) const [with T = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;; mpl_::false_ = mpl_::bool_&lt;false&gt;]</b>’
<b>/usr/include/boost/serialization/export.hpp:133:20:</b>   required from ‘<b>const boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;&amp; boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;::export_guid() const [with T = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;]</b>’
<b>/home/thaer/pagmo2/src/islands/fork_island.cpp:380:1:</b>   required from here
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:63:12:</b> <font color="#EF2929"><b>error: </b></font>cannot derive from ‘<b>final</b>’ base ‘<b>pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;</b><b>’ in derived ty</b>pe ‘<b>boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::boost_type_traits_internal_struct_X</b>’
     struct <font color="#EF2929"><b>boost_type_traits_internal_struct_X</b></font> : public Derived, virtual Base
            <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
/usr/include/boost/type_traits/is_virtual_base_of.hpp: In instantiation of ‘<b>struct boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::boost_type_traits_internal_struct_Y</b>’:
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:80:5:</b>   required from ‘<b>const bool boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::value</b>’
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:88:4:</b>   required from ‘<b>const bool boost::detail::is_virtual_base_of_impl2&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;::value</b>’
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:97:45:</b>   required from ‘<b>struct boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/mpl/if.hpp:63:11:</b>   required from ‘<b>struct boost::mpl::if_&lt;boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_virtual_base&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_primitive&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt; &gt;</b>’
<b>/usr/include/boost/mpl/eval_if.hpp:37:41:</b>   required from ‘<b>struct boost::mpl::eval_if&lt;boost::is_virtual_base_of&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_virtual_base&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt;, boost::mpl::identity&lt;boost::serialization::void_cast_detail::void_caster_primitive&lt;pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, pagmo::detail::isl_inner_base&gt; &gt; &gt;</b>’
<b>/usr/include/boost/serialization/void_cast.hpp:279:17:</b>   [ skipping 15 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
<b>/usr/include/boost/serialization/export.hpp:86:1:</b>   required from ‘<b>struct boost::archive::detail::ptr_serialization_support&lt;boost::archive::binary_iarchive, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/archive/detail/register_archive.hpp:25:8:</b>   required from ‘<b>struct boost::archive::detail::_ptr_serialization_support&lt;boost::archive::binary_iarchive, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt; &gt;</b>’
<b>/usr/include/boost/archive/binary_iarchive.hpp:57:1:</b>   required by substitution of ‘<b>template&lt;class Serializable&gt; typename boost::archive::detail::_ptr_serialization_support&lt;boost::archive::binary_iarchive, Serializable&gt;::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, boost::archive::binary_iarchive*, boost::archive::detail::adl_tag) [with Serializable = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;]</b>’
<b>/usr/include/boost/serialization/export.hpp:123:38:</b>   required from ‘<b>void boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;::export_guid(mpl_::false_) const [with T = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;; mpl_::false_ = mpl_::bool_&lt;false&gt;]</b>’
<b>/usr/include/boost/serialization/export.hpp:133:20:</b>   required from ‘<b>const boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;&amp; boost::archive::detail::extra_detail::guid_initializer&lt;T&gt;::export_guid() const [with T = pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;]</b>’
<b>/home/thaer/pagmo2/src/islands/fork_island.cpp:380:1:</b>   required from here
<b>/usr/include/boost/type_traits/is_virtual_base_of.hpp:71:12:</b> <font color="#EF2929"><b>error: </b></font>cannot derive from ‘<b>final</b>’ base ‘<b>pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;</b>’ in derived type ‘<b>boost::detail::is_virtual_base_of_impl&lt;pagmo::detail::isl_inner_base, pagmo::detail::isl_inner&lt;pagmo::fork_island&gt;, boost::integral_constant&lt;bool, true&gt; &gt;::boost_type_traits_internal_struct_Y</b>’
     struct <font color="#EF2929"><b>boost_type_traits_internal_struct_Y</b></font> : public Derived
            <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
CMakeFiles/pagmo.dir/build.make:75: recipe for target &apos;CMakeFiles/pagmo.dir/src/islands/fork_island.cpp.o&apos; failed
make[2]: *** [CMakeFiles/pagmo.dir/src/islands/fork_island.cpp.o] Error 1
CMakeFiles/Makefile2:83: recipe for target &apos;CMakeFiles/pagmo.dir/all&apos; failed
make[1]: *** [CMakeFiles/pagmo.dir/all] Error 2
Makefile:145: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

**Comment by galopes** [comment]
I'm having the same problem... Did you manage to solve it?

**Comment by jschueller** [comment]
you need boost>=1.68, see #503

**Comment by bluescarni** [comment]
Thanks to @jschueller the bumped Boost requirement will be in the next version, so I will close this report. Please re-open if needed.
