### ISSUE TITLE
Some tiny spelling errors

### ISSUE THREAD

**Issue by pgrt** [esa/pagmo2#513]
Hello,

I am a Debian developer, working on the packaging of pagmo2 in Debian. I noticed a spelling error, repeated 4 times: "algortihm" instead of "algorithm".

The enclosed patch corrects all those occurrences.

Best,
Pierre
[spelling.txt](https://github.com/esa/pagmo2/files/8766365/spelling.txt)

**Comment by bluescarni** [comment]
I think these spelling mistakes were fixed in #518 , please re-open if this is not the case.
