### ISSUE TITLE
how to run pagmo2 in parallel  cluster?

### ISSUE THREAD

**Issue by alexbrownsoft** [esa/pagmo2#527]
I would like to run pagmo2 on the cluster. But i noted that pagmo2 doesn't support mpi, how can i ultilize massive cluster to run optimization?

Is there any guidance or example for the massive optimization?

**Comment by bluescarni** [comment]
@alexbrownsoft cluster support is not available in pagmo2. In pygmo2, you can use the ipyparallel island to distribute computations over a cluster:

https://esa.github.io/pygmo2/islands.html#pygmo.ipyparallel_island
