### ISSUE TITLE
Question about get_bounds()

### ISSUE THREAD

**Issue by IlefatKion** [esa/pagmo2#573]
This library is of a great help! Thanks to everyone contributing!

I am lookig at possible ways to use 2 different box bounds for my optimization problem. this means that the problem should be contained by one of the 2 bounds. Does anyone have a clue to do so?

Thanks..

**Comment by darioizzo** [comment]
If the bounds are disconnected I think the only option is to instantiate and evolve 2 different problems. (assuming i understood the question)

**Comment by darioizzo** [comment]
This is not an issue rather a question. Closing it.

**Comment by IlefatKion** [comment]
Thanks for your answer!
