### ISSUE TITLE
UDP and archipelago

### ISSUE THREAD

**Issue by jmllorens** [esa/pagmo2#83]
I have noticed that when I try the archipelago class in a python user defined problem (UDP), pygmo needs somehow to connect to an iPython Cluster. Instead, with a predefined problem, everything runs smoothly in my box. 
Is there anyway to avoid the configuration of an iPython Cluster?

This is the code I am using for this test:

```
import pygmo as pg

class sphere_function:
        def __init__(self, dim):
            self.dim = dim
   
        def fitness(self, x):
            return [sum(x*x)]
   
        def get_bounds(self):
            return ([-1] * self.dim, [1] * self.dim)
   
        def get_name(self):
            return "Sphere Function"
   
        def get_extra_info(self):
            return "\tDimensions: " + str(self.dim)

prob = pg.problem(sphere_function(3))
algo = pg.algorithm(pg.bee_colony(gen = 20, limit = 20))
archi = pg.archipelago(n=1, algo=algo, prob=prob, pop_size=10)
```

**Comment by bluescarni** [comment]
@jmllorens are you on Python 2?

**Comment by jmllorens** [comment]
Yes, sorry, I should have mentioned it.

**Comment by bluescarni** [comment]
For pagmo2 we made the decision to require ``ipyparallel`` for parallel operations in Python 2 Linux. The reasons have to do with some technical details about how the ``multiprocessing`` module works in Python 2 in a Linux environment. Basically, it boils down to the fact that Python 2 in Linux does not allow us to enforce a behaviour of the parallel bits of pagmo consistent with the behaviour on other platforms and/or Python 3.

Note that you don't need an actual cluster to run pygmo in parallel with ipyparallel. You just need to run the
```
ipcluster start
```
command in a separate shell. This will setup a "local" cluster with a number of processes equal to the number of cores on your machine. After the cluster has been started, you can fire up pygmo and everything should work.

**Comment by jmllorens** [comment]
It works without problems now. Seems a good decision. I was a bit scared at first, because even without cluster, sometimes a few files should be edited. But the setup of ipcluster is rather straightforward.

Migration to pagmo2 completed for my current optimization.

Thanks for your help.

**Comment by bluescarni** [comment]
No problem!

Note that there are missing features in the current archipelago wrt pagmo 1.x (the topology/migration bits are not there yet). We will add them back soon.
