### ISSUE TITLE
Topology in pagmo2

### ISSUE THREAD

**Issue by slm2020** [esa/pagmo2#85]
Hello,

It seems that the topology classes from pagmo are not present it pagmo2. Is there a good way to achieve similar migration between islands in pagmo2 (pygmo, specifically) as it currently exists? If not, will topology functionality be implemented in the future? 

Thank you!

Steve

**Comment by darioizzo** [comment]
It is indeed the next thing we are going to work on. But you will have to wait some weeks unfortunately.

Currently we are busy packaging ....

**Comment by slm2020** [comment]
Thanks for the reply! Looking forward to it.

**Comment by darioizzo** [comment]
#102 is addressing this request.

**Comment by wardzin** [comment]
Update on the topology/migration feature?

Also, how important is island migration in terms of optimization quality?

**Comment by darioizzo** [comment]
The topology/migration feature is under development. The reason it is taking so long is to be found in our development model that tends to favour small incremental changes over big ones. 

As to your question on how much it counts for the optimization quality, my experience is that it does quite a lot, you can read about it on our paper "generalized island model" on the section called " migrate or not migrate"

**Comment by wardzin** [comment]
I see. If I want island migration, what options do I have in terms of a Python optimization library? Would I have to use PyGMO 1? Are there any other similarly advanced Python libraries that support island migration (other than the first version of PyGMO)?

**Comment by bluescarni** [comment]
Migration is now available in pagmo 2.11, released today.

Note that not all topologies have been ported from pagmo 1 (we have at the moment the ``unconnected``, ``ring`` and ``fully_connected`` topologies). We will gradually add the missing topologies in the next few weeks.
